README.md
The current one is not a valid link on the site.
=>  Update link to Mckernel.

Cargo.lock, src/arch/x86_64/kernel/processor.rs
@jschwe Can you check this PR on your system. This should solve issue #30.
=> check if tsc_frequency determines a valid value

src/arch/x86_64/kernel/processor.rs, src/runtime_glue.rs
This patch should solve #45. @jounathaen Can you test it also on your system?
=> call shutdown, if a panic is triggered

src/arch/x86_64/kernel/processor.rs, src/runtime_glue.rs
in addition, I create PR gz/rust-cpuid#33 to simplify the function
=> improve the hypervisor detection

.github/workflows/test.yml, .travis.yml
we combine both branches and are able to use per default master branch
=> use master branch of rusty-hermit to test the kernel

src/arch/x86_64/kernel/apic.rs, src/arch/x86_64/kernel/percore.rs, src/kernel_message_buffer.rs, src/scheduler/mod.rs, src/scheduler/task.rs
=> improve alignment of data between cores

src/arch/x86_64/kernel/processor.rs
- frequency is delivered in KHz (and not Hz)
- fix conversion to MhZ
=> fix interpretation of hypervisor_info

Cargo.lock, src/arch/x86_64/kernel/processor.rs
=> use cpuid to determine if the kernel runs on a hypervisor

README.md
reduce README size to solve issue #76
=> slim down README

src/arch/x86_64/kernel/virtio_net.rs, src/drivers/net/mod.rs, src/mm/mod.rs, src/syscalls/mod.rs
- required to support hermit-playground
=> add support of a C user-space

README.md
Now the README only contains the necessary information and links to the RustyHermit page
=> Slimmed down README

src/arch/x86_64/mm/paging.rs
- using of mem::transmute to reinterpret a pointer
=> remove compiler warnings

.github/workflows/test.yml, Cargo.lock, Cargo.toml, src/lib.rs, src/mm/allocator.rs, tests/common/mod.rs
- revise allocator interface
- reenable tests on macOS
=> revise allocator interface to support the latest version of libstd

.travis.yml, src/runtime_glue.rs
These changes are required to support the latest nightly compiler.
=> introduce __rg_oom, which is called by libstd due a oom error

.github/workflows/docker.yml, .github/workflows/format.yml, .github/workflows/test.yml, .travis.yml, CMakeLists.txt, Cargo.lock, Cargo.toml, aarch64-unknown-hermit-kernel.json, src/arch/x86_64/mm/paging.rs, src/mm/allocator.rs, src/mm/hole.rs, src/mm/mod.rs, src/scheduler/mod.rs, src/synch/recmutex.rs, src/syscalls/tasks.rs, x86_64-unknown-hermit-kernel.json
- using of VirtAddr also for newlib-based applications
=> port libhermit to support C-based applications

src/mm/mod.rs
Most of #110 is already merged to kernel. This pull request is a collection of missing changes.
=> Revision of PR #110

.github/dependabot.yml
=> Enabled dependabot for Cargo and Github Actions

Cargo.toml, src/arch/x86_64/kernel/mod.rs, src/arch/x86_64/kernel/processor.rs, src/arch/x86_64/kernel/switch.s, src/arch/x86_64/kernel/switch_fsgsbase.s
by detecting the FSGSBASE support, the dispatcher will be patched to support it
=> add support of processors, which doesn't support FSGSBASE

Cargo.toml, build.rs, src/lib.rs
=> remove unneeded dependency to git

src/arch/x86_64/kernel/irq.rs, src/arch/x86_64/kernel/pic.rs, src/drivers/net/mod.rs
=> Take ExceptionStackFrame by value

x86_64-unknown-hermit-kernel.json
Same as https://github.com/hermitcore/rusty-loader/pull/18.
=> Update data layout to include new x86 address spaces

src/drivers/net/mod.rs, src/drivers/net/rtl8139.rs, src/drivers/net/virtio_net.rs, src/drivers/virtio/virtqueue/mod.rs, src/drivers/virtio/virtqueue/packed.rs, src/drivers/virtio/virtqueue/split.rs, tests/basic_math.rs, tests/basic_mem.rs, tests/common/mod.rs, tests/measure_startup_time.rs
I automatically applied all possible clippy suggestions. I'll have a look at manual fixes for the remaining warnings in other PRs.
What do you think?
=> Automatically apply clippy suggestions

src/arch/x86_64/kernel/apic.rs, src/arch/x86_64/kernel/processor.rs, src/arch/x86_64/kernel/scheduler.rs, src/arch/x86_64/mm/paging.rs
Follow up to #196, where I forgot some places.
=> Take more `ExceptionStackFrame`s by value

src/arch/x86_64/kernel/fuse.rs, src/arch/x86_64/kernel/pci.rs, src/drivers/virtio/mod.rs, src/drivers/virtio/transport/pci.rs, src/drivers/virtio/virtqueue/mod.rs, src/scheduler/mod.rs, src/scheduler/task.rs
These clippy fixes only appear in newer nightlies than we currently use, but fixing them early makes upgrading the toolchain easier in the future.
=> Clippy fixes for latest nightly

.github/workflows/clippy.yml
Reverts hermitcore/libhermit-rs#216
=> Revert "Don't override nightly for clippy CI"

src/synch/semaphore.rs
This is a rather opinionated change regarding code readability.
In my code editor with four spaces per tab, the extra scope looks quite weird. By explicitly dropping the guard instead, I personally find this easier to read. What do you think?
=> Semaphore: Drop guard explicitly for readability

src/logging.rs, src/macros.rs
Resolves https://github.com/hermitcore/libhermit-rs/issues/224.
=> Improve macro hygiene

src/drivers/net/virtio_net.rs, src/drivers/virtio/depr/virtio.rs, src/drivers/virtio/depr/virtio_fs.rs, src/drivers/virtio/depr/virtio_net.rs, src/drivers/virtio/env.rs, src/drivers/virtio/mod.rs, src/drivers/virtio/transport/pci.rs, src/drivers/virtio/virtqueue/mod.rs, src/synch/spinlock.rs
This pull request fixes some typos.
=> fix some typos

src/drivers/net/mod.rs, src/scheduler/task.rs, src/syscalls/mod.rs, src/syscalls/tasks.rs
- the new interface is required for hermitcore/rusty-hermit#117
- in principle, it reopens #176
=> new interface to the network driver

.github/workflows/aarch64.yml, .github/workflows/x86.yml, .gitlab-ci.yml, rust-toolchain.toml
Closes https://github.com/hermitcore/libhermit-rs/issues/269, https://github.com/hermitcore/libhermit-rs/issues/265.
=> Upgrade nightly version of hermit to nightly-2021-08-31

.github/dependabot.yml
Same as https://github.com/hermitcore/uhyve/pull/174
=> Improve dependabot config

src/arch/x86_64/kernel/switch.rs
Closes https://github.com/hermitcore/libhermit-rs/issues/266.
=> kernel_function: Use clobber_abi

.github/workflows/aarch64.yml, .github/workflows/x86.yml, .gitlab-ci.yml, tests/hermit_test_runner.py
Fixes https://github.com/hermitcore/libhermit-rs/issues/273.
=> QEMU: Enable xsaveopt cpu feature

src/drivers/net/mod.rs, src/drivers/net/rtl8139.rs, src/drivers/net/virtio_net.rs, src/syscalls/interfaces/mod.rs, src/syscalls/mod.rs
Fixes https://github.com/hermitcore/libhermit-rs/issues/279.
=> Implement sys_free_tx_buffer

README.md
Closes https://github.com/hermitcore/libhermit-rs/issues/291
=> README: Fix Slack link

.cargo/config.toml, .github/workflows/x86.yml, rust-toolchain.toml
See
* https://github.com/hermitcore/rusty-hermit/issues/167
=> Upgrade to recent nightly channel

tests/thread.rs
See
* https://github.com/hermitcore/rusty-hermit/issues/170
=> Tests: Add test_thread_local

.github/workflows/aarch64.yml, .github/workflows/x86.yml
See https://github.com/hermitcore/rusty-hermit/pull/186/commits/c19b63d31bdb6b2ea6167b2008ee7a82e5a8162a
=> CI: Install cargo-binutils

src/arch/aarch64/kernel/scheduler.rs, src/arch/x86_64/kernel/scheduler.rs, src/scheduler/mod.rs, src/scheduler/task.rs, src/syscalls/tasks.rs
Replaces https://github.com/hermitcore/libhermit-rs/pull/317.
=> Clarify sys_clone behavior

src/arch/aarch64/kernel/mod.rs, src/arch/x86_64/kernel/CMakeLists.txt, src/arch/x86_64/kernel/apic.rs, src/arch/x86_64/kernel/boot.asm, src/arch/x86_64/kernel/mod.rs
entry.asm was replaced with _start in d36871a7e6828ad72e6b063b1fd68246ada15b81.
=> Cleanup entry.asm remains

.github/workflows/publish_docs.yml
See https://github.com/hermitcore/libhermit-rs/pull/334.
=> CI: Install NASM in docs workflow

Cargo.toml, rust-toolchain.toml, src/arch/aarch64/kernel/irq.rs, src/arch/aarch64/kernel/mod.rs, src/arch/aarch64/kernel/processor.rs, src/arch/aarch64/kernel/serial.rs, src/arch/aarch64/kernel/start.rs, src/arch/aarch64/mm/paging.rs, src/arch/x86_64/kernel/acpi.rs, src/arch/x86_64/kernel/irq.rs, src/arch/x86_64/kernel/percore.rs, src/arch/x86_64/kernel/processor.rs, src/arch/x86_64/kernel/scheduler.rs, src/arch/x86_64/kernel/start.rs, src/arch/x86_64/kernel/switch.rs, src/drivers/virtio/virtqueue/packed.rs, src/drivers/virtio/virtqueue/split.rs, src/lib.rs, src/syscalls/interfaces/uhyve.rs
Fixes https://github.com/hermitcore/libhermit-rs/issues/321.
=> Upgrade toolchain channel to 2022-01-05

src/drivers/net/rtl8139.rs
This addresses https://github.com/hermitcore/libhermit-rs/issues/348.
I replaced the manual pointer arithmetic with boxed slices which contain bounds checks (no unsafe code accessing the buffers in the driver now). Now reading outside the buffers through manipulated lengths should be impossible. It is still possible to access the other network packages in the buffers. I am not sure about the architecture of the network driver and where to get the corresponding lengths from, which might or might not require a bigger rework.
@lrapp-x41-pub, would you consider this enough for closing https://github.com/hermitcore/libhermit-rs/issues/348 or would that require to properly avoid accessing all of the buffer?
While working on this I found https://github.com/hermitcore/libhermit-rs/issues/355.
=> RTL: RAII buffers

src/arch/x86_64/kernel/mod.rs, src/arch/x86_64/kernel/percore.rs, src/arch/x86_64/kernel/processor.rs, src/arch/x86_64/kernel/switch.rs, src/arch/x86_64/mm/mod.rs, src/environment.rs, src/lib.rs, src/logging.rs, src/mm/allocator.rs, src/mm/hole.rs
Closes https://github.com/hermitcore/libhermit-rs/issues/233.
=> Enable `unsafe_op_in_unsafe_fn`

src/arch/x86_64/kernel/mmio.rs, src/arch/x86_64/kernel/pci.rs, src/arch/x86_64/kernel/vga.rs, src/drivers/net/rtl8139.rs, src/drivers/net/virtio_mmio.rs, src/drivers/virtio/transport/mmio.rs, src/lib.rs, src/syscalls/lwip.rs
See https://github.com/hermitcore/libhermit-rs/issues/397.
=> Fix clippy lints

.github/workflows/aarch64.yml, .github/workflows/x86.yml, .gitlab-ci.yml
This reverts commit 70e1b5a6332ce2bddc69dce59dae9e4bd5fcf054.
=> Revert "[REVERT] CI: Pin RustyHermit for xtask"

.github/workflows/publish_docs.yml
Fixes 6d0d0ff0d0c3942467a77399258a885d01fa430c
=> Fixup: CI: Specify target for publish_docs

xtask/src/main.rs
Closes https://github.com/hermitcore/libhermit-rs/issues/397.
=> xtask: Run clippy with no and all features

src/arch/aarch64/kernel/mod.rs, src/arch/mod.rs, src/arch/x86_64/kernel/apic.rs, src/arch/x86_64/kernel/irq.rs, src/arch/x86_64/kernel/mod.rs, src/arch/x86_64/kernel/percore.rs, src/arch/x86_64/kernel/processor.rs, src/arch/x86_64/kernel/scheduler.rs, src/console.rs, src/lib.rs, src/mm/allocator.rs, src/mm/freelist.rs, src/mm/hole.rs, src/mm/mod.rs, src/mm/test.rs, src/runtime_glue.rs, src/syscalls/interfaces/uhyve.rs, src/syscalls/mod.rs
Our aarch64 target does not target the "hermit" os anymore.
=> Remove target_os = "hermit" checks

Dockerfile
See https://github.com/hermitcore/rusty-hermit/pull/243
=> Remove cargo-download

.github/workflows/x86.yml
Support for windows has been added to the Makefile upstream.
=> Don't modify the loader's Makefile

.github/workflows/x86.yml, bors.toml
Something is wrong with QEMU: https://github.com/hermitcore/libhermit-rs/runs/6109029660
=> [Revert] Disable Windows CI for now

src/macros.rs, src/syscalls/random.rs
Note that this changes and stabilizes the API of the affected two functions.
=> Random: Make sys_secure_* functions extern "C"

.github/workflows/x86.yml, bors.toml
Reverts hermitcore/libhermit-rs#427
=> Revert "[Revert] Disable Windows CI for now"

.gitlab-ci.yml
This reverts commit 57f2f3637ade9ea27be1713acc347ace67abf2a4.
=> Revert "print debug messages during test run"

Cargo.toml, src/arch/x86_64/kernel/fuse.rs, src/arch/x86_64/kernel/mod.rs, src/arch/x86_64/kernel/pci.rs, src/arch/x86_64/kernel/switch.rs, src/arch/x86_64/mm/paging.rs, src/arch/x86_64/mm/physicalmem.rs, src/arch/x86_64/mm/virtualmem.rs, src/drivers/net/mod.rs, src/drivers/net/virtio_mmio.rs, src/drivers/net/virtio_net.rs, src/drivers/virtio/mod.rs, src/env.rs, src/lib.rs, src/mm/freelist.rs, src/scheduler/mod.rs, src/scheduler/task.rs, src/synch/semaphore.rs, src/syscalls/fs.rs
Closes https://github.com/hermitcore/libhermit-rs/issues/364.
=> Remove dead code

rust-toolchain.toml, src/macros.rs, xtask/src/main.rs
Depends on https://github.com/rust-lang/rust/pull/95365.
=> Don't export __rg_oom

src/scheduler/mod.rs, src/scheduler/task.rs, src/syscalls/tasks.rs
To avoid priority inversion, I added system calls to changes the priority. They will be used by the PR https://github.com/hermitcore/rust/commit/dd7e2582764844c2e53876658732977a249b3190.
=> add system calls to change the priority of a task

Dockerfile, rust-toolchain.toml, src/arch/x86_64/kernel/pci.rs, src/drivers/net/virtio_net.rs, src/drivers/virtio/mod.rs, src/drivers/virtio/transport/pci.rs, src/drivers/virtio/virtqueue/mod.rs
Closes https://github.com/hermitcore/libhermit-rs/pull/474.
=> Upgrade to nightly-2022-06-29

src/arch/aarch64/kernel/processor.rs, src/arch/aarch64/mm/paging.rs, src/arch/x86_64/kernel/apic.rs, src/arch/x86_64/kernel/fuse.rs, src/arch/x86_64/kernel/processor.rs, src/arch/x86_64/mm/paging.rs, src/drivers/net/rtl8139.rs, src/drivers/net/virtio_net.rs, src/drivers/virtio/virtqueue/mod.rs, src/drivers/virtio/virtqueue/packed.rs, src/drivers/virtio/virtqueue/split.rs, src/scheduler/mod.rs, src/scheduler/task.rs
This pull request fixes several typos.
=> fix several typos

src/synch/semaphore.rs
Exponential backoff is only usefull for SMP machines because another
task has to release the semaphore. Without a context switch, this task
must run on another core.
=> Disable exponential backoff for non-smp machines

src/net/device.rs, src/net/mod.rs, src/synch/spinlock.rs
in addition, the PR enables nested interrupts if try_lock fails
=> increase the readability of the spinlock implementations

xtask/src/archive.rs
See https://github.com/hermitcore/rusty-hermit/issues/374#issuecomment-1289479322.
CC: @wucke13
=> xtask: Print description for llvm_tools::Error::NotFound

src/mm/mod.rs
I created https://github.com/hermitcore/libhermit-rs/pull/601 to catch these automatically.
=> mm: Paging rework fixup for newlib

src/scheduler/mod.rs
I created https://github.com/hermitcore/libhermit-rs/pull/601 to catch these automatically.
=> scheduler: Fix newlib without smp

.github/workflows/ci.yml
Closes https://github.com/hermitcore/libhermit-rs/issues/573.
=> CI: Check all features

src/scheduler/mod.rs, src/scheduler/task.rs
Closes https://github.com/hermitcore/libhermit-rs/issues/624.
=> Fix spurious page faults

Cargo.lock, Cargo.toml, src/arch/aarch64/kernel/scheduler.rs, src/arch/aarch64/mm/paging.rs, src/arch/x86_64/kernel/acpi.rs, src/arch/x86_64/kernel/apic.rs, src/arch/x86_64/kernel/mmio.rs, src/arch/x86_64/kernel/scheduler.rs, src/drivers/virtio/depr/virtio_net.rs, src/drivers/virtio/virtqueue/mod.rs, src/drivers/virtio/virtqueue/packed.rs, src/drivers/virtio/virtqueue/split.rs, src/macros.rs, src/mm/allocator.rs, src/mm/freelist.rs, src/mm/hole.rs, src/mm/mod.rs, src/mm/test.rs
Closes https://github.com/hermitcore/libhermit-rs/issues/564.
=> Migrate to align-address crate

src/fd/socket/mod.rs
The check should be done by the implementation of the trait.
=> remove check of the backlog parameter

Cargo.lock, Cargo.toml, src/fd/socket/tcp.rs, src/net/device.rs, src/net/mod.rs, src/syscalls/net.rs
revise interface configuration to support the new version of smoltcp
=> bump smoltcp from 0.8.2 to 0.9.1

Cargo.lock
See [dependabot alert](https://github.com/hermitcore/libhermit-rs/security/dependabot/1)
=> update Cargo.lock to remove Dependabot alert #1

rust-toolchain.toml
-  includes the new socket interface
=> switch to the latest nightly compiler

Cargo.lock, Cargo.toml, src/fd/file.rs, src/fd/mod.rs, src/fs/fuse.rs, src/lib.rs, src/syscalls/fs.rs, src/syscalls/mod.rs
- use num_trait to handle SeekWhence
=> add lseek support for the FUSE interface

src/arch/x86_64/mm/physicalmem.rs
the gap is used to realize for memory-mapped IO (e.g. APIC)
=> define the same 32bit gap like uhyve

src/env.rs, src/syscalls/interfaces/mod.rs
=> remove trailing null characters

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/arch/aarch64/kernel/interrupts.rs, src/arch/aarch64/kernel/processor.rs, src/arch/aarch64/kernel/scheduler.rs, src/arch/mod.rs
- add timer support
- using the counter-timer physical count register to determine a timestamp
- using rusty_demo to test the aarch64 port
- solves #738
=> using arm-gic to programm the ARM Generic Interrupt Controller

src/scheduler/task.rs
=> using pop_front instead pop_back
=> take always the oldest task from the queue

src/fd/socket/mod.rs
fix https://github.com/hermitcore/libhermit-rs/issues/778
=> fix(udp): fix udp create error.

Cargo.lock, Cargo.toml, src/executor/device.rs
Closes https://github.com/hermitcore/libhermit-rs/pull/780.
=> Upgrade smoltcp to 0.10

src/drivers/net/mod.rs, src/drivers/net/virtio_net.rs, src/executor/device.rs
with this feature the driver is able to skip checksumming of packets
=> add support of VIRTIO_NET_F_GUEST_CSUM

Cargo.toml, src/drivers/mod.rs, src/drivers/pci.rs, src/drivers/virtio/mod.rs, src/drivers/virtio/transport/pci.rs, src/lib.rs, src/mm/mod.rs, src/syscalls/fs.rs
=> add option to disable filesystem support

src/drivers/net/virtio_net.rs
Closes https://github.com/hermitcore/libhermit-rs/issues/823.
=> `virtio_net`: Fix `invalid_reference_casting`

src/executor/network.rs
If a network device is used, where corrupted messages isn't possible, a network timer for retransmission isn't required. In this case, programming of the timer interrupt isn't required.
=> avoid unneeded programming of the timer interrupt

.github/workflows/ci.yml, .github/workflows/publish_docs.yml, Cargo.lock, Cargo.toml, README.md, src/arch/aarch64/mm/paging.rs, src/macros.rs, xtask/src/main.rs
GitHub-Closes: https://github.com/hermitcore/kernel/issues/35
=> feat: rename crate to hermit-kernel

.github/workflows/ci.yml
See https://github.com/hermit-os/hermit-rs/pull/470.
=> ci: change UDP port to 9975

src/scheduler/task.rs
Closes https://github.com/hermit-os/kernel/issues/898
=> fix(scheduler): move cursor creation to first use

.github/workflows/ci.yml, rust-toolchain.toml, xtask/src/arch.rs, xtask/src/build.rs, xtask/src/ci/qemu.rs, xtask/src/clippy.rs
Closes https://github.com/hermit-os/kernel/issues/955
=> fix(rust-toolchain.toml): remove `x86_64-unknown-none`

src/arch/aarch64/kernel/processor.rs, src/arch/aarch64/kernel/systemtime.rs, src/arch/mod.rs, src/arch/riscv64/kernel/systemtime.rs, src/arch/x86_64/kernel/systemtime.rs, src/executor/device.rs, src/executor/network.rs, src/fs/mem.rs, src/syscalls/timer.rs, src/time.rs
This is best reviewed commit by commit.
=> fix: overflow in time calculation on AArch64

src/fs/mem.rs
- add check if the directory entry is a file
=> unlink is only able to delete a file

src/fd/eventfd.rs, src/fd/socket/tcp.rs, src/fd/socket/udp.rs, src/fd/stdio.rs, src/fs/mem.rs
This addresses https://github.com/hermit-os/kernel/pull/1052#discussion_r1488246293.
=> refactor(PollEvent): simplify flag propagation

src/fd/eventfd.rs
This addresses https://github.com/hermit-os/kernel/pull/1052#discussion_r1488242928.
=> refactor(eventfd): use `ready!` to extract `Poll::Ready`

src/errno.rs, src/lib.rs, src/macros.rs
Keep a copy of the the error number in TLS
=> add error number in thread local storage

src/fd/mod.rs, src/fs/mod.rs, src/syscalls/mod.rs
- `close` in trait ObjectInterface is never used => remove it
=> remove obsolete code

Cargo.toml, src/errno.rs, src/lib.rs
Use https://github.com/hermit-os/no_std for  as example.
=> introduce feature flag `nostd` to boot the kernel without `std`

.github/workflows/ci.yml, xtask/src/build.rs
Closes https://github.com/hermit-os/kernel/issues/743
=> feat(xtask): add support for building with cargo-careful

src/drivers/net/virtio_net.rs
For reading information from the prepared Ethernet frame, uses smoltcp methods instead of hardcoded offsets to fields.
=> virtio_net: use smoltcp methods instead of hardcoding field offsets

xtask/src/ci/qemu.rs
See https://github.com/hermit-os/loader/issues/338
=> fix(microvm): explicitly disable ACPI

src/drivers/net/virtio_pci.rs, src/drivers/virtio/transport/pci.rs
=> fix(virtio/pci): compare capabilities length with proper struct size

hermit-macro/src/system.rs, src/syscalls/condvar.rs, src/syscalls/entropy.rs, src/syscalls/futex.rs, src/syscalls/lwip.rs, src/syscalls/mod.rs, src/syscalls/processor.rs, src/syscalls/recmutex.rs, src/syscalls/semaphore.rs, src/syscalls/socket.rs, src/syscalls/spinlock.rs, src/syscalls/system.rs, src/syscalls/tasks.rs, src/syscalls/timer.rs
Extern C functions were not externally available due to a missing no_mangle.
=> Added no_mangle to all extern C functions

src/syscalls/mod.rs, src/syscalls/socket.rs
See https://github.com/hermit-os/hermit-rs/pull/581.
=> feat(syscall): add `sys_shutdown` in favor of `sys_shutdown_socket`

src/arch/aarch64/kernel/scheduler.rs, src/arch/x86_64/kernel/processor.rs, src/arch/x86_64/kernel/scheduler.rs, src/executor/device.rs, src/fd/socket/udp.rs, src/lib.rs, src/scheduler/mod.rs, src/shell.rs, src/syscalls/semaphore.rs, tests/common/mod.rs, tests/thread.rs
In addition, reduce the dependency between the kernel and the syscall interface.
=> introduce public interface to shutdown the system

src/executor/device.rs
=> add warning if HERMIT_IP is set and dhcpv4 feature is enabled

README.md
Added riscv64 build description.
=> Added riscv64 build description

Cargo.toml, src/arch/x86_64/kernel/mod.rs, src/arch/x86_64/mm/physicalmem.rs, src/lib.rs
=> feat(x86_64): print FDT

src/arch/aarch64/mm/physicalmem.rs, src/arch/riscv64/mm/physicalmem.rs, src/arch/x86_64/mm/physicalmem.rs
Extracted from https://github.com/hermit-os/kernel/pull/1140
Best reviewed commit by commit.
=> refactor(physicalmem): minor adjustments

rust-toolchain.toml, src/arch/riscv64/kernel/scheduler.rs, src/arch/x86_64/kernel/apic.rs, src/drivers/pci.rs, src/fd/socket/tcp.rs
The latest compiler include rust-lang/rust#126346 and rust-lang/rust#126135
=> switch to the lastest nightly compiler

src/drivers/virtio/transport/mmio.rs, src/drivers/virtio/transport/pci.rs, src/drivers/virtio/virtqueue/packed.rs, src/drivers/virtio/virtqueue/split.rs, virtio-spec/src/pci.rs
I found these while working on https://github.com/hermit-os/kernel/pull/1273.
Best reviewed commit by commit.
=> fix(virtqueue): fix driver notifications

.github/workflows/ci.yml
This reverts commit f39b92d72af61bc95632e47fdd86b34b228a6f18.
=> Revert "ci: allow failing rftrace in release mode"

src/fd/socket/tcp.rs
- specification is published at https://datatracker.ietf.org/doc/html/rfc793
- close hermit-os/hermit-rs#602
=> fix state machine of the progress engine

Cargo.lock, Cargo.toml, src/drivers/fs/virtio_fs.rs, src/drivers/net/virtio/mmio.rs, src/drivers/net/virtio/mod.rs, src/drivers/net/virtio/pci.rs, src/drivers/virtio/virtqueue/mod.rs, src/drivers/virtio/virtqueue/packed.rs, src/drivers/virtio/virtqueue/split.rs, src/fs/fuse.rs
=> refactor(virtq): use proper types for buffer elements

Cargo.lock, Cargo.toml, src/fs/fuse.rs
Check error codes more consistently and fix incorrect assumptions. Probably fixes #1260.
=> fuse: improve error handling

src/drivers/net/virtio/mod.rs
Now that each packet uses two buffer elements (one for the header and one for the content), we need to push half as many packets to the queue as the size of the queue.
=> fix(net/virtio): push the correct number of packets to the queue

src/arch/riscv64/mm/virtualmem.rs, src/synch/recmutex.rs, src/syscalls/entropy.rs, src/syscalls/mod.rs, src/syscalls/recmutex.rs, src/syscalls/tasks.rs, xtask/src/clippy.rs
Fixes https://github.com/hermit-os/kernel/issues/470
=> fix(xtask): enable clippy for `feature = "newlib"`

src/arch/aarch64/mm/virtualmem.rs, src/arch/riscv64/mm/virtualmem.rs, src/arch/x86_64/mm/virtualmem.rs, src/mm/mod.rs, src/syscalls/mod.rs, src/syscalls/tasks.rs
Depends on https://github.com/hermit-os/newlib/pull/6.
=> feat(newlib): remove `sbrk`

src/drivers/net/virtio/mod.rs, src/drivers/virtio/transport/mmio.rs, src/drivers/virtio/transport/pci.rs, src/drivers/vsock/mod.rs, src/syscalls/socket.rs
Improvements are derived from @cagatay-y comments to hermit-os/kernel#826
=> improve the compatibility to the virtio standard

src/fd/mod.rs, src/fd/socket/udp.rs
block_on polls also a certain teim on the device
=> remove obsolete usage of poll_on

src/mm/mod.rs
Closes https://github.com/hermit-os/kernel/issues/1427
=> refactor(mm): memory check

src/arch/x86_64/mm/paging.rs
=> fix(x86_64/paging): UEFI preparation

xtask/src/doc.rs
For https://github.com/hermit-os/kernel/pull/1442.
=> fix(xtask): build docs for each arch separately

src/arch/x86_64/kernel/apic.rs
=> fix(apic): disable PIT interrupt

src/arch/aarch64/kernel/mod.rs, src/arch/riscv64/kernel/mod.rs, src/arch/x86_64/kernel/mod.rs, src/arch/x86_64/kernel/serial.rs, src/arch/x86_64/mm/virtualmem.rs, src/console.rs, src/executor/mod.rs, src/executor/vsock.rs, src/fd/stdio.rs, src/syscalls/table.rs
- add Wakers for async handling of the input stream
- fix heap size of the monolithic approach
=> revise handling of the serial device 

src/fd/stdio.rs
This was probably forgotten in https://github.com/hermit-os/kernel/pull/1393.
=> refactor(stdio): migrate to `uhyve-interface`

src/arch/x86_64/mm/paging.rs
=> fix(paging): support huge pages in debug function

src/fd/mod.rs, src/fd/stdio.rs, src/scheduler/mod.rs, src/syscalls/mod.rs
=> add syscalls corresponding to dup2 and isatty

src/arch/x86_64/kernel/processor.rs
See https://github.com/hermit-os/uhyve/pull/876.
=> feat(processor): read TSC frequency from FDT

src/arch/x86_64/kernel/mod.rs
This extension is required to create a monolithic kernel based on Hermit OS
=> extend jump_to_user_land to pass arguments to the user space

src/arch/riscv64/kernel/devicetree.rs, src/arch/riscv64/kernel/mmio.rs
Issue found with @marcomaas1990.
=> fix(riscv64): finalize MMIO drivers

.github/workflows/ci.yml, src/arch/x86_64/mm/paging.rs, src/mm/mod.rs
This PR adds support for the remaining paging functions on UEFI and sets up VIRTIO on UEFI.
=> fix: VIRTIO on UEFI

Cargo.lock, Cargo.toml, src/arch/x86_64/kernel/mod.rs, src/arch/x86_64/kernel/scheduler.rs, src/arch/x86_64/mm/mod.rs, src/arch/x86_64/mm/paging.rs, src/arch/x86_64/mm/physicalmem.rs, src/arch/x86_64/mm/virtualmem.rs, src/mm/mod.rs
The commit *fix(x86_64/mm): identity-map physical memory* closes https://github.com/hermit-os/uhyve/issues/426.
=> feat: use identity-mapped page tables instead of recursive ones

src/arch/aarch64/kernel/interrupts.rs, src/arch/aarch64/kernel/pci.rs
Instead of defaulting to core 0 for interrupt handling use the local cpu to dispatch interrupts. This allows for the handling of PPIs.
=> feat(aarch64-interrupts): use local cpuid for interrupts

src/scheduler/task.rs
=> refactor: Use inline const to initialize priority queue

src/mm/device_alloc.rs, src/mm/physicalmem.rs
This increases bandwidth from 400 Mbit/s to 550 Mbit/s for me.
=> perf(device_alloc): don't re-map device memory

.github/workflows/ci.yml
This PR is required if hermit-os/hermit-rs#689 is merged.
=> rename wasmtime tests

hermit-builtins/exports, hermit-builtins/src/math.rs
These symbols were introduced in https://github.com/hermit-os/kernel/pull/1709.
=> feat(libm): export new symbols

src/drivers/virtio/virtqueue/mod.rs
Currently, we were allocating a two-item `VecDeque` on the heap with talc for every call to `{PackedVq, SplitVq}::try_recv`, which is horribly inefficient. The reason I presume this was done before was to have cheap `pop_front` operations, but since they usually only contain two items, moving around all the items of a smallvec is super cheap anyways and we can skip the conversion and allocation.
We may want to replace this with a smallvec equivalent of `VecDeque` in the future, but there is no such struct yet and we currently don't really need it either.
Results in a ~15% improvement in TCP bandwidth for me.
=> perf(virtqueue): Use smallvec for UsedDeviceWritableBuffer

src/arch/x86_64/kernel/processor.rs
When compiling on a CPU with AVX512 support and `-C target-cpu=native` for the application, I would see the following before this change:
```rs
[0][INFO] Jumping into application
[0][ERROR] Invalid Opcode (#UD) Exception: InterruptStackFrame {
instruction_pointer: VirtAddr(
0x840ac1,
),
code_segment: SegmentSelector {
index: 1,
rpl: Ring0,
},
cpu_flags: RFlags(
RESUME_FLAG | IOPL_LOW | INTERRUPT_FLAG | 0x2,
),
stack_pointer: VirtAddr(
0x40003811c7e0,
),
stack_segment: SegmentSelector {
index: 2,
rpl: Ring0,
},
}
```
This is because XCR0 is not configured properly for AVX512. See also https://wiki.osdev.org/CPU_Registers_x86#XCR0 - we need to toggle the right bits for AVX512 support and then be able to save the ZMM registers.
This makes the binary run just fine. 
I see the following now: …
=> feature(arch/x86_64): Configure XCR0 and save ZMM registers for AVX512

hermit-macro/src/lib.rs, hermit-macro/src/system.rs, src/macros.rs, src/syscalls/mmap.rs, src/syscalls/mod.rs, src/syscalls/recmutex.rs, src/syscalls/semaphore.rs, src/syscalls/socket.rs, src/syscalls/spinlock.rs, src/syscalls/tasks.rs, src/syscalls/timer.rs
This also fixes early returns combined with strace.
=> fix(syscall): make setting errno explicit

.github/workflows/ci.yml, xtask/src/ci/qemu.rs
This is useful for adding virtio-console support in https://github.com/hermit-os/kernel/pull/1781.
=> xtask: unify qemu devices argument

src/macros.rs
This is possible since we removed lwIP.
Closes https://github.com/hermit-os/kernel/issues/471.
=> fix(macros): switch to kernel stack on newlib

.github/workflows/ci.yml, xtask/src/ci/qemu.rs
This depends on https://github.com/hermit-os/hermit-rs/pull/763.
=> ci: test stdin example

src/arch/x86_64/kernel/mod.rs, src/fd/mod.rs, src/scheduler/mod.rs, src/scheduler/task.rs
We don't ever hold a guard over an `.await` point anyway.
=> feat(scheduler): don't lock `Task::object_map` asynchronously

src/syscalls/socket/addrinfo.rs, src/syscalls/socket/mod.rs
This is best reviewed commit by commit.
This PR depends on https://github.com/hermit-os/kernel/pull/1777 and https://github.com/hermit-os/kernel/pull/1800.
=> feat: implement getaddrinfo

.github/workflows/ci.yml, Cargo.toml, src/arch/aarch64/kernel/mod.rs, src/arch/riscv64/kernel/devicetree.rs, src/arch/riscv64/kernel/mod.rs, src/arch/x86_64/kernel/mod.rs, src/config.rs, src/drivers/mmio.rs, src/drivers/mod.rs, src/drivers/net/mod.rs, src/drivers/pci.rs, src/drivers/virtio/mod.rs, src/drivers/virtio/transport/pci.rs, src/init_cell.rs
=> feat(drivers/net): Make virtio-net optional, take 2

.gitignore
Add files that are needed to run or are generated during tests.
=> add test related files to gitignore

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/arch/aarch64/kernel/start.rs, xtask/src/arch.rs, xtask/src/ci/qemu.rs, xtask/src/clippy.rs
=> feat: aarch64_be support
