hermit-os/kernel

- rust-toolchain
This is useful for all of us not living on nightly as default.
> Added rust-toolchain file pointing to nightly.

- src/arch/x86_64/kernel/pci.rs
- src/drivers/net/uhyve.rs
Redoing this PR since last one was merging the wrong branch.
This PR should solve #17 
When detecting PCI devices, we check if the vendor ID is of RedHat virtio (0x1AF4). This closely matches the C code for virtio device detection.
You can test this by running:
```qemu-system-x86_64 -display none -smp 1 -m 64M -serial stdio  -kernel loader/target/$(target)-loader/$(rdir)/hermit-loader -initrd tests/target/$(target)/$(rdir)/rusty_tests -cpu qemu64,apic,fsgsbase,pku,rdtscp,xsave,fxsr -netdev user,id=mynet0 -device virtio-net,netdev=mynet0```
You should see a info log saying "Found virtio device with device id $ID"
> Implemented virtio device detection

- src/arch/x86_64/kernel/mod.rs
This PR is necessary for [this issue](https://github.com/hermitcore/uhyve/issues/1) with [this PR](https://github.com/hermitcore/uhyve/pull/2) to run as it removes the requirement for the running environment to not be uhyve.
> Remove check for uhyve in PCI

- README.md
Use make to be consistent with the gitlab pipeline.
Without the objcpy after building the loader, qemu fails at startup.
I initially wanted to create the pull request for the devel branch, but the Readme at the devel branch seems to be outdated.
> Readme: Fix build instructions for Qemu

- src/arch/x86_64/kernel/processor.rs
detect_from_cpuid could previously set CpuFrequency to zero.
To ensure that this doesn't happen all detect methods set
mhz and CpuFrequencySources via a helper method that ensures
that mhz is never explicitly set to zero (apart from the
creation of the object)
> Ensure CpuFrequency is never explicitly set to zero

- .vscode/settings.json
Without these changes, VS code would compile the project correctly
> Fixed VS code config

- README.md
- src/environment.rs
- src/syscalls/interfaces/mod.rs
- src/util.rs
I was annoyed with having to recompile my benchmark each time I wanted to change some options, so I implemented a new kernel-command-line option to set argv/c.
Previously, there were only `-freq` and `-proxy`, both set some kernel-internal stuff.
This pull request adds a new option `-args`. Since I did not want it to clash with any existing (or future) options which might get introduced, I wrote a simple "tokenizer" which can handle splitting strings at spaces while respecting quoted strings.
Exampe cmdline:
```
qemu-system-x86_64 -cpu qemu64,fsgsbase,rdtscp,xsave,fxsr,+x2apic -enable-kvm \
-display none -smp 1 -m 1G -serial stdio -kernel LOADER -initrd APP \
-append "-args '-a -b --opt \"some string\"'"
--> argv = ["{name}", "-a", "-b", "--opt", "some string"]
```
If you want to have a …
> Add new kernel-command-line option for setting argv

- src/arch/x86_64/kernel/scheduler.rs
This commit aims to improve the Error message when panicing after Allocation of Memory for the TaskStacks has failed. This should make it clearer to a User, that increasing the amount of memory the Machine has will solve this problem. 
The current panic message is `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src\arch\x86_64\kernel\scheduler.rs:92:25` which doesn't say much without looking at the Code.
Since `expect` is basically `unwrap` with a custom Error message, this shouldn't have any performance implications.
> Scheduler: Improve Error message when Memory allocation fails

- src/arch/x86_64/kernel/pci.rs
- src/arch/x86_64/kernel/virtio.rs
- src/arch/x86_64/kernel/virtio_fs.rs
- src/arch/x86_64/kernel/virtio_net.rs
- src/mm/mod.rs
- src/syscalls/mod.rs
I have refactored pci.rs a bit. Changes:
- handle both IOSpace and 32/64-bit Memory BARs
- add generic function to mm: map(), which maps a physical buffer to a newly allocated virtual address range, used for mmaping memory bars
- add function to memory map the PCI memory bars
- check pci device header-type to ensure we don't read/write garbage, warn on multifunction devices
- remove sys_pci_find_adapter, since it is not used anywhere
- I am unsure of its original purpose, since I did not find any reference in newlib/hermit-abi. Does it have a current / planned future use?
Previously, virtio mapped the pci bars with the `Cache Disable` page-flag set. Since @stlankes introduced memory barriers, this should no longer be needed.
I have not tested these changes with virtio-net, only virtio-fs. …
> Cleanup of pci.rs

- .travis.yml
This commits adds testing of `libhermit-rs` for pushes and PRs. Both debug and release builds are tested with 1 and 2 cores each.
Tests are done via the rusty-hermit demo in rusty-hermit. rusty-hermit is cloned and checked out to the devel branch. The demo is then compiled with the version of libhermit-rs that triggered the build and not the version specified as a submodule in rusty-hermit.
rusty-hermit including libhermit-rs is compiled fresh every time, but cargo dependencies such as uhyve and cargo-download are cached to speed up build time
> CI: Test libhermit-rs on uhyve with rusty-demo

- src/logging.rs
Adds support to change the LevelFilter of the logger at compile time via enviroment variable `HERMIT_LOG_LEVEL_FILTER`. 
If the Environment variable is not set, or the name doesn't match, then `LevelFilter::Info` is used by default, which is the same as it was before.
The name of the Environment variable is arbitrary of course, so feel free to suggest other names.
> Log: Add option to set LevelFilter at compile time

- .github/workflows/test.yml
Update: This PR is ready for review.
I think the rusty-hermit demo should be run here as a test. Right now we only check if PRs compile and do a quick cargo test. Checking if the rusty-hermit demo is able to run succesfully improves the testing situation.
Changes: 
- Run the rusty-hermit demo (see rusty-hermit repo) on PRs and all pushes 
- Add support for running the demo with qemu on windows and macOS ~~( SMP doesn't work consistently, but thats a different issue - https://github.com/hermitcore/rusty-hermit/issues/12~~ issue solved with 34114700c13a8c34808a5cfd699dd1e20b7796bc)
- ~~Workaround build failing by using old nightly (see also https://github.com/hermitcore/rusty-hermit/issues/7~~ This was fixed by disabling lto in rusty-hemit)
> CI: Run rusty-hermit demo tests on PRs to libhermit-rs

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/syscalls/fs.rs
- requires PR rust-lang/rust#71839
- consequently, the latest nightly compiler has to be used
> remove dependency to lazy_static

- src/arch/x86_64/kernel/apic.rs
- src/arch/x86_64/kernel/gdt.rs
- src/arch/x86_64/kernel/mod.rs
- src/arch/x86_64/kernel/percore.rs
- src/arch/x86_64/kernel/processor.rs
- src/arch/x86_64/kernel/systemtime.rs
- src/kernel_message_buffer.rs
Don't merge. I'm just opening the pull request so I can use the pipeline.
- Make detect_from_hypervisor safe and make it more clear that it currently only supports detection from uhyve.
- Replace std::intrinsics::volatile_load with core::ptr::read_volatile
- Replace std::intrinsics::volatile_store with core::ptr::write_volatile
> WIP: Improvement/refactoring

- src/lib.rs
- src/scheduler/mod.rs
scheduler::init has nothing to do and can be removed
> remove obsolete init function

- src/arch/x86_64/kernel/start.rs
- this is a suggestion of the Rust documentation
> revise entry code to use only inline assembly in the naked function

- .github/workflows/test.yml
Since we aren't downloading from cargo.io cargo download isn't actually needed in this workflow, so it doesn't have to be installed.
> CI: Remove cargo download step

- src/lib.rs
- src/syscalls/interfaces/uhyve.rs
- src/syscalls/mod.rs
This PR adresses the Safety of the internal `malloc`, `free` and `realloc` functions. 
- Add Errors section to docs
- Check if parameters (size > 0, generated layout) are valid and warn/return an error if this is not the case
- Mark as **unsafe** 
- Add detailed Safety section (relevant sections taken from the internally used unsafe functions)
- Suggestion: Maybe we could add some structure that tracks the pointers created/destroyed with malloc/realloc and free? If we did that, I think we could make them safe again, but this would cause a performance overhead. Comments?
- make internal block unsafe and add Todos and Fixmes since this still needs some work!
- Suggestion: I would personally like to change the whole signature of the trait and return some structure which is not so close to c. …
> Safety: Mark __sys_realloc and __sys_free as unsafe

- src/collections/cachepadded.rs
- src/collections/mod.rs
- src/synch/spinlock.rs
it is derived from crossbeam-utils, the main difference is that this version provides a constant initialization routine
> add generic to align types

- src/arch/mod.rs
- src/arch/x86_64/kernel/mod.rs
- src/console.rs
As you can see here: https://github.com/hermitcore/rusty-hermit/pull/31, printing non ascii strings doesn't work on qemu, while it does work on uhyve. I'm not really sure why it works on uhyve, but I guess that the Write traits are probably implemented somewhere else. @stlankes Do you know more about this?
This PR adds support for printing non-ASCII characters to the console.
- Swap order of write_char and write_str to match order of trait
- Implement write_char by calling write_str to match the implementation in the standard library (and support non-ascii characters)
- Add output_message_buf for printing of a buffer.
- Convert str to UTF-8 encoded byte buffer before printing.
> Add UTF-8 support to Console

- src/arch/x86_64/kernel/scheduler.rs
- src/scheduler/mod.rs
- src/syscalls/tasks.rs
HermitCore doesn't have a full round-robin scheduler.
It is designed to map a thread to a single core.
Only in cooperation a thread switch to another thread.
> remove any support of round-robin scheduling

- src/arch/mod.rs
- src/arch/x86_64/kernel/switch.rs
- src/scheduler/mod.rs
- reduce the number of interrupts
> set task switch flag only if the FPU ownership is able to switch

- src/arch/x86_64/kernel/virtio_net.rs
- src/drivers/net/mod.rs
- src/scheduler/mod.rs
- src/syscalls/mod.rs
- network thread is able to wakeup directly the blocked threads
- reduce the number of context switches
> introduce a new interface for smoltcp

- src/arch/x86_64/kernel/scheduler.rs
- src/scheduler/mod.rs
- store task (instead of the task id) in the finished task queue
- it delays the release of the task (and its stacks) until the context switch has been completed
- create TLS only if TLS isn't already initialized
> safer allocation / deallocation of task stacks

- src/arch/x86_64/kernel/pci.rs
- src/arch/x86_64/kernel/virtio.rs
- src/arch/x86_64/kernel/virtio_net.rs
- src/collections/mod.rs
- src/drivers/net/mod.rs
- src/lib.rs
- src/syscalls/interfaces/mod.rs
By transferring a packet to Virtio, the driver will be set in polling mode. In this mode, all Virtio interrupts are disabled. Every 20ms, the driver checks, if the user space is still sending packets. If not, the polling mode will be disabled.
> reduce the number of interrupts during a send operation

- Cargo.lock
- src/arch/x86_64/kernel/acpi.rs
- src/arch/x86_64/kernel/apic.rs
- src/arch/x86_64/kernel/gdt.rs
- src/arch/x86_64/kernel/irq.rs
- src/arch/x86_64/kernel/mod.rs
- src/arch/x86_64/kernel/pci.rs
- src/arch/x86_64/kernel/scheduler.rs
- src/arch/x86_64/kernel/virtio.rs
- src/arch/x86_64/kernel/virtio_fs.rs
- src/arch/x86_64/kernel/virtio_net.rs
- src/arch/x86_64/mm/mod.rs
- src/arch/x86_64/mm/paging.rs
- src/arch/x86_64/mm/physicalmem.rs
- src/arch/x86_64/mm/virtualmem.rs
- src/environment.rs
- src/lib.rs
- src/mm/allocator.rs
- src/mm/mod.rs
- src/scheduler/mod.rs
- src/scheduler/task.rs
- src/syscalls/interfaces/uhyve.rs
- the logical address space is completly separate from the physical
- consequently, different names are used
> separate virtual from physical addresses

- .cargo/config
- .github/workflows/test.yml
- .travis.yml
- Cargo.toml
- src/arch/mod.rs
- src/arch/x86_64/kernel/apic.rs
- src/arch/x86_64/kernel/irq.rs
- src/arch/x86_64/kernel/mod.rs
- src/arch/x86_64/kernel/percore.rs
- src/arch/x86_64/kernel/processor.rs
- src/arch/x86_64/kernel/scheduler.rs
- src/console.rs
- src/environment.rs
- src/lib.rs
- src/macros.rs
- src/mm/allocator.rs
- src/mm/freelist.rs
- src/mm/hole.rs
- src/mm/mod.rs
- src/mm/test.rs
- src/rlib.rs
- src/runtime_glue.rs
- src/syscalls/interfaces/uhyve.rs
- src/syscalls/mod.rs
- tests/basic_math.rs
- tests/basic_mem.rs
- tests/basic_print.rs
- tests/common/mod.rs
- tests/hermit_test_runner.py
- tests/measure_startup_time.rs
This PR aims to add integration tests to rusty-hermit. This PR consists mostly of the framework necessary, and only contains some basic tests, which realistically don't have a very high quality.  None of the rusty-demo tests have been moved here either (yet). 
The PR mainly adds hermit_test_runner.py which can run the integration tests built by `cargo test --target [...]` either on uhyve or on qemu. 
There are still a couple of open ToDos and points that might need some discussion / rework, so I'm opening this as a draft. I'll also improve the Description of the PR next week when I have a bit more time.
The integration tests can executed by calling:
`cargo test --tests --no-fail-fast -Z build-std=core,alloc --target x86_64-unknown-hermit-kernel [-- [Test Runner arguments]]`
Valid Test …
> Integration tests

- .cargo/config
afterwards `cargo build` without any additional flag builds libhermit-rs for x86_64
> build per default the target x86_64-unknown-hermit-kernel

- .github/workflows/test.yml
- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/scheduler/mod.rs
- src/scheduler/task.rs
- tests/thread.rs
- PR should solve issues #105
- add integration test to show this behavior
- make sure that the task is always added to the list of blocked task => avoid "loosing" of tasks
> avoid deadlock when multiple cores are available

- src/mm/allocator.rs
- src/mm/hole.rs
- these changes are required to support the latest version of the nightly compiler
> Rename AllocErr to AllocError

- .github/workflows/docker.yml
- .github/workflows/format.yml
- .github/workflows/nightly.yml
- GitHub deprecate the set-env and add-path commands
- use the [guideline](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files) to solve this issue
> fix broken CI

- CMakeLists.txt
The kernel isn't allowed to use SSE instructions. The workaround is to build two versions of basic functions like `memcpy`. One for kernel-, one for user-space.
> rename basic functions like memcpy to avoid collisions with the user space

- .cargo/config
- CMakeLists.txt
- don't rename symbols for newlib
> activate assembly support for basic function (e.g. memcpy)

- .github/workflows/nightly.yml
- src/arch/x86_64/kernel/apic.rs
- src/lib.rs
- src/scheduler/mod.rs
ICR programming should be not-interruptable to avoid corrupted values
> disable interrupts during programming of the ICR

- .github/workflows/nightly.yml
Closes #122 
- Fixes the Windows CI.
- Force qemu install to the latest working version
- The November 2020 release doesn't seem to be working, even when
adjusting the path to the new install location install 'C:\Program Files (x86)'
> CI: Fix and reenable windows tests

- CMakeLists.txt
- src/arch/x86_64/kernel/gdt.rs
- src/arch/x86_64/kernel/idt.rs
- src/arch/x86_64/kernel/processor.rs
- src/arch/x86_64/mm/paging.rs
- src/arch/x86_64/mm/physicalmem.rs
- src/logging.rs
- src/mm/mod.rs
Especially with a C-base user space the subsystem doesn't align GDT/IDT correctly. In addition, the initial page table wasn't correctly initialized and triggers sometimes page faults.
> revision of the memory subsystem initialization

- src/synch/spinlock.rs
Backing off in spin loops reduces contention and improves overall performance.
> using a exponential backoff to realize a spinlock

- src/arch/x86_64/kernel/pci.rs
- src/arch/x86_64/kernel/virtio.rs
- src/arch/x86_64/kernel/virtio_fs.rs
- src/syscalls/fs.rs
- disable interrupts during the initialization of pci devices
- add support of relative paths
- in case of virtio-fs the file system uses a static location as working directory
- the location is definable at compile time by setting the environment variable `HERMIT_WD`
> revise virtio-fs integration

- Cargo.lock
- Cargo.toml
- src/arch/x86_64/mm/mod.rs
- src/arch/x86_64/mm/paging.rs
- src/arch/x86_64/mm/physicalmem.rs
- minor changes are required to initialize the multiboot information
> switching to crate "multiboot 0.6"

- .gitlab-ci.yml
- rust-toolchain
- src/arch/x86_64/kernel/processor.rs
- tests/hermit_test_runner.py
This adds the --timeout flag to `hermit_test_runner.py`. For now the value is simply a positive integer meaning a timeout in seconds.
The default timeout is 300 seconds.
This timeout applies to all integration tests (as in each integration test may take up to timeout seconds).
> Tests: Add timeout for integration tests

- src/arch/x86_64/kernel/pci.rs
- src/drivers/mod.rs
- src/drivers/net/mod.rs
- src/drivers/net/rtl8139.rs
- src/drivers/net/virtio_net.rs
- src/drivers/virtio/mod.rs
- src/drivers/virtio/transport/pci.rs
- src/mm/mod.rs
- add driver for the network interface Realteak 8139
- this interface is often emulated by hypervisors or emulators like Qemu
- to support different network interface, the tait `NetworkInterface` is introduced as abstraction layer
> add RTL8139 driver

- src/synch/semaphore.rs
the previous version is able to switch to another core, if a task is available
> call scheduler only if the task has to block

- .cargo/config
- CMakeLists.txt
- rust-toolchain
- explicit activation of optimized core functions (e.g. memcpy) isn't longer required
> switch to the latest nightly compiler

- .gitlab-ci.yml
Conseuently, we disable some host features to avoid bugs like https://bugs.launchpad.net/ubuntu/+source/qemu/+bug/1884470.
> specifiy the prefered CPU

- Cargo.lock
- Cargo.toml
The workaround should solve issue hermitcore/libhermit-rs#164 and is only necessry until gz/rust-x86#71 is accepted.
> clearify license text, add workround to use raw-cpuid

- src/drivers/net/virtio_net.rs
- src/drivers/virtio/mod.rs
- src/drivers/virtio/transport/pci.rs
- src/drivers/virtio/virtqueue/mod.rs
- src/drivers/virtio/virtqueue/packed.rs
- src/drivers/virtio/virtqueue/split.rs
I hope this type of PR does not annoy you :) but I believe the correct spelling is [initial](https://www.oxfordlearnersdictionaries.com/spellcheck/english/?q=inital)
> spelling police: inital -> initial

- rust-toolchain
- src/drivers/virtio/transport/pci.rs
in addition, we update the toolchain to the latest version
> fix device number of the legacy virtio network device

- .cargo/config
- rust-toolchain
- src/arch/x86_64/kernel/acpi.rs
- src/arch/x86_64/kernel/apic.rs
- rename kernel target to support the latest toolchain
- minor changes to avoid rust-lang/rust#82523
- add latest supported toolchain as default toolchain
> rename kernel target

- rust-toolchain
- src/arch/x86_64/kernel/start.s
- src/arch/x86_64/kernel/switch.s
- src/arch/x86_64/kernel/switch_fsgsbase.s
global_asm switch per default to the intel syntax, because the behaviour is than similiar to inline assembly. libhermit-rs follow this step and switch to the same default syntax.
See also rust-lang/rust#84107
> switch to intel syntax for assembly code

- src/arch/mod.rs
- src/arch/x86_64/kernel/apic.rs
- src/arch/x86_64/kernel/fuse.rs
- src/arch/x86_64/kernel/scheduler.rs
- src/arch/x86_64/mm/physicalmem.rs
- src/arch/x86_64/mm/virtualmem.rs
- src/drivers/net/mod.rs
- src/drivers/net/virtio_net.rs
- src/drivers/virtio/depr/virtio.rs
- src/drivers/virtio/depr/virtio_net.rs
- src/drivers/virtio/mod.rs
- src/drivers/virtio/transport/pci.rs
- src/drivers/virtio/virtqueue/mod.rs
- src/drivers/virtio/virtqueue/packed.rs
- src/drivers/virtio/virtqueue/split.rs
- src/lib.rs
- src/macros.rs
- src/mm/freelist.rs
- src/mm/hole.rs
- src/synch/semaphore.rs
- src/syscalls/fs.rs
- src/syscalls/mod.rs
These are a bunch of fixes for clippy warnings.
In some circumstances, where fixing is not straightforward, I allowed the lints instead.
Together with the other clippy PRs, there shouldn't be any clippy warnings now, so we can enable those in CI in the future.
What do you think?
> Fix clippy warnings

- src/arch/x86_64/mm/paging.rs
- src/drivers/net/rtl8139.rs
- src/drivers/net/virtio_net.rs
- src/drivers/virtio/virtqueue/packed.rs
- src/lib.rs
We currently set `clippy::all` to `warn`. Some lints from `clippy::all` are `deny` by default. This removes our relaxation and fixes all errors.
What do you think?
> Fix clippy errors

- tests/basic_math.rs
Fixes
```
error[E0658]: use of unstable library feature 'bench_black_box'
--> tests/basic_math.rs:18:5
|
18 | use core::hint::black_box;
|     ^^^^^^^^^^^^^^^^^^^^^
|
= note: see issue #64102 <https://github.com/rust-lang/rust/issues/64102> for more information
= help: add `#![feature(bench_black_box)]` to the crate attributes to enable
```
when building tests.
> Enable bench_black_box for basic_math test

- src/drivers/virtio/virtqueue/mod.rs
- src/drivers/virtio/virtqueue/packed.rs
We can create `&mut` to fields without having to resort to raw pointers.
> virtqueue: Avoid going over unsafe raw ptrs

- src/drivers/virtio/virtqueue/mod.rs
While working on more clippy lints, I noticed something that seems to by an issue caused by copy-pasting.
We surely don't want to treat send buffers as receive buffers, right?
> virtqueue: Fix using send buffer as recieve buffer

- .github/workflows/clippy.yml
Now that clippy warnings are fixed, we can enforce clippy checks via CI.
> CI: Add clippy workflow

- .github/workflows/clippy.yml
We want to use clippy from the nightly specified in `toolchain.toml` instead of using the latest nightly.
> Don't override nightly for clippy CI

- src/drivers/net/virtio_net.rs
Workaround for #209. Introduced in https://github.com/hermitcore/libhermit-rs/commit/a9fc0530473911d00caf2357a6dad69e034e92b6.
> RxQueues::get_next: Explicitly bind transfer

- src/runtime_glue.rs
Depends on https://github.com/hermitcore/rusty-hermit/pull/139.
Having weak linkage on the handlers does no harm but is not necessary after the before mentioned PR.
> Strongly link panic and oom handlers

- bors.toml
Now that we have a stable Clippy CI, we can enforce Clippy lints via bors.
> Enforce clippy via bors

- src/console.rs
- src/syscalls/interfaces/mod.rs
Fixes #238.
I also made the constructor of `Console` private. Where's the fun in locking a `Console`, when everyone can create new ones?
> Fix `Console` unsoundness

- src/config.rs
- src/lib.rs
This determines `HW_DESTRUCTIVE_INTERFERENCE_SIZE` at compile time from `crossbeam-utils`.
> Get destructive interference size from crossbeam

- src/arch/aarch64/kernel/processor.rs
- src/arch/x86_64/kernel/processor.rs
- src/scheduler/task.rs
`NonZeroU64::leading_zeros` has recently been stabilized.
Now we can make our `msb` helper function portable, resulting in the same `x86_64` assembly: [Compiler Explorer](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(fontScale:14,fontUsePx:'0',j:1,lang:rust,selection:(endColumn:8,endLineNumber:3,positionColumn:8,positionLineNumber:3,selectionStartColumn:5,selectionStartLineNumber:3,startColumn:5,startLineNumber:3),source:'%23!!%5Bfeature(asm)%5D%0A%0Ause+std::num::NonZeroU64%3B%0A%0Apub+fn+old_msb(n:+u64)+-%3E+Option%3Cu64%3E+%7B%0A%09if+n+%3E+0+%7B%0A%09%09let+ret%3B%0A%09%09unsafe+%7B%0A%09%09%09asm!!(%22bsr+%7B%7D,+%7B%7D%22,+out(reg)+ret,+in(reg)+n,+options(pure,+nomem,+nostack))%3B%0A%09%09%7D%0A%09%09Some(ret)%0A%09%7D+else+%7B%0A%09%09None%0A%09%7D%0A%7D%0A%0Apub+fn+new_msb(n: …
> Make msb helper function portable

- src/arch/x86_64/kernel/acpi.rs
- src/arch/x86_64/kernel/apic.rs
87a9d3f9ef7acfd9e8f2188f27457e275ea9a925 was wrong.
Instead of calculating an address at one place in `acpi`, it read from that address.
The warning in `apic` was due to an implicit borrow and can be resolved by an explicit copy into a let binding.
> Remove unintended dereference

- src/arch/x86_64/kernel/mod.rs
- src/arch/x86_64/kernel/scheduler.rs
- src/arch/x86_64/kernel/switch.rs
- src/drivers/net/mod.rs
- src/lib.rs
- src/macros.rs
- src/scheduler/mod.rs
- src/syscalls/condvar.rs
- src/syscalls/lwip.rs
- src/syscalls/mod.rs
- src/syscalls/processor.rs
- src/syscalls/random.rs
- src/syscalls/recmutex.rs
- src/syscalls/semaphore.rs
- src/syscalls/spinlock.rs
- src/syscalls/system.rs
- src/syscalls/tasks.rs
- src/syscalls/timer.rs
This fixes https://github.com/hermitcore/libhermit-rs/issues/234 introduced in https://github.com/hermitcore/libhermit-rs/commit/41cf625c33801690f5be566db67e3eec5b372feb.
As described in https://github.com/hermitcore/libhermit-rs/issues/234, the issue with the old implementation was inlining resulting in wrongly managing stack space after the switch, potentially resulting in a page fault, when writing before the new stack:
```rust
fn sys_foo() {
// reserves stack space for `a` (`rsp -= 16`)
switch_rsp();
// use reserved stack space (`[rsp + 16]`), even though rsp is not the same anymore
let a = [0_u8; 16];
}
```
To my knowledge, inlining can only be really prevented, by explicitly `call`ing the function in assembly.
I fixed this issue in five steps:
1. Remove `switch_to_kernel!`, …
> Fix switching to kernel stack

- src/arch/x86_64/kernel/switch.rs
- src/macros.rs
- src/syscalls/mod.rs
- src/syscalls/random.rs
Fixes https://github.com/hermitcore/libhermit-rs/issues/250.
This also improves documentation regarding the design of `kernel_function!`.
Supersedes https://github.com/hermitcore/libhermit-rs/pull/251.
> Fixup: Relay bigger types over pointers for affected kernel functions

- Cargo.lock
* updating proc-macro2 v1.0.26 -> v1.0.27
* updating raw-cpuid v9.0.0 -> v9.1.1
* updating syn v1.0.72 -> v1.0.73
`proc-macro2` and `syn` should be painless, because these are only patch version updates.
`raw-cpuid` should be no hassle, too, if it follows semver - and its readme says it does. :)
> update dependencies / lockfile

- src/arch/x86_64/kernel/switch.rs
If the type in a register is smaller than the register, Rust assumes the upper bits in the register to be zero.
For example, checking a `bool` might happen via `test edi, edi`, although the type only occupies `dil`.
> kernel_function: Clear upper bits of register

- Cargo.lock
- Cargo.toml
- src/arch/x86_64/kernel/processor.rs
- Bumps x86 from 0.40.0 to 0.41.0.
- The new version breaks the interface and requires source code modifications.
- see https://github.com/gz/rust-cpuid/blob/aaaa6e6fc07d04850f6119732b950d3a8383173b/CHANGELOG.md
> Bump x86 from 0.40.0 to 0.41.0

- .cargo/config.toml
- .github/workflows/x86.yml
- rust-toolchain.toml
Reverts hermitcore/libhermit-rs#292
hermitcore/libhermit-rs#292 this was not meant to be merged yet. See hermitcore/rusty-hermit#170.
I was sure, bors would play nicely with draft PRs nowadays. Sorry.
bors r+
> Revert "Upgrade to recent nightly channel"

- src/drivers/virtio/transport/mmio.rs
@simonschoening reports that the current implementation doesn't work on RISC-V. By using `write_volatile` we should get a more platform independent solution.
> using write_volatile to guarantee that the data is written to the I/O device

- .gitlab-ci.yml
- src/arch/aarch64/kernel/bootinfo.rs
- src/arch/aarch64/kernel/mod.rs
- src/arch/aarch64/kernel/scheduler.rs
- src/arch/x86_64/kernel/mod.rs
- src/arch/x86_64/kernel/scheduler.rs
- src/environment.rs
- src/lib.rs
Closes https://github.com/hermitcore/rusty-hermit/issues/170. :tada: 
Replaces https://github.com/hermitcore/libhermit-rs/pull/305.
Depends on:
* https://github.com/hermitcore/rusty-loader/pull/46
* https://github.com/hermitcore/uhyve/pull/241
The cause of the issue is the calculation of the thread pointer:
```python
thread_ptr = tls_block_ptr + round(tls_len, 32)
thread_ptr = tls_block_ptr + round(tls_len, tls_align)
```
This is fixed in the first two commits of this PR.
The later commits completely rework the `TaskTLS` struct. I did this to better understand the problem. The old comments were partly outdated and wrong. Also the code was not very rusty. I replaced manual memory allocations with `Box`es and restructured and recommented the code.
> Fix thread pointer calculation, rework TaskTLS

- .cargo/config.toml
- .github/workflows/x86.yml
- rust-toolchain.toml
- src/arch/mod.rs
- src/arch/x86_64/kernel/apic.rs
- src/arch/x86_64/kernel/irq.rs
- src/arch/x86_64/kernel/mod.rs
- src/arch/x86_64/kernel/percore.rs
- src/arch/x86_64/kernel/processor.rs
- src/arch/x86_64/kernel/scheduler.rs
- src/console.rs
- src/lib.rs
- src/mm/allocator.rs
- src/mm/freelist.rs
- src/mm/hole.rs
- src/mm/mod.rs
- src/mm/test.rs
- src/runtime_glue.rs
- src/syscalls/interfaces/uhyve.rs
- src/syscalls/mod.rs
Reopens https://github.com/hermitcore/libhermit-rs/pull/292.
Replaces https://github.com/hermitcore/libhermit-rs/pull/302.
See https://github.com/hermitcore/rusty-hermit/pull/169.
> Upgrade to recent nightly channel

- src/arch/x86_64/kernel/gdt.rs
without this fix, the processor assumes that a I/O permission map is available
> fix limit of the TSS descriptor

- .dockerignore
- .gitlab-ci.yml
- Dockerfile
- rust-toolchain.toml
This rewrites the Dockerfile and moves all dependencies into the docker image, where dependencies are compiled modularly on their respective toolchains.
Note that this moves the base image from `ubuntu:latest` to `debian:bullseye`.
> Rework Dockerfile

- src/arch/x86_64/kernel/apic.rs
If the ACPI detections fails of is disabled, RustyHermit uses the (old) MultiProcessor Specification to detect the Local APIC and the IO-APIC.
> determine Local APIC and IO-APIC by the MultiProcessor Specification

- src/arch/x86_64/kernel/mod.rs
- src/arch/x86_64/kernel/processor.rs
- src/environment.rs
If `parse_command_line` isn't able to identify the processor frequency, the function `get_command_line_cpu_frequency` will return `None` instead of a invalid frequency.
In addition, the frequency measurement with PIT is able to fail. In this case, we just guess a frequency of 2Ghz. For tests is guessing a good workaround.
> add option that COMMAND_LINE_CPU_FREQUENCY is invalid

- Cargo.toml
- src/arch/aarch64/kernel/bootinfo.rs
- src/arch/aarch64/kernel/irq.rs
- src/arch/aarch64/kernel/mod.rs
- src/arch/aarch64/kernel/processor.rs
- src/arch/aarch64/kernel/serial.rs
- src/arch/aarch64/kernel/start.rs
- src/arch/aarch64/kernel/start.s
- src/arch/aarch64/kernel/stubs.rs
- src/arch/aarch64/mm/paging.rs
- src/console.rs
- src/lib.rs
- src/logging.rs
- src/macros.rs
- src/runtime_glue.rs
- src/syscalls/interfaces/uhyve.rs
- inline wrapper functions
- don't use a thread-safe version to initialize the kernel logger
because at this stage the kernel doesn't provide threads
- simplifies the boot process
> synchronize aarch64 port to x86 port

- .gitlab-ci.yml
- src/lib.rs
This is required for integration tests.
> Make _print public again

- src/environment.rs
- src/syscalls/interfaces/mod.rs
This PR makes it possible to overwrite the default network parameters for IP address, gateway and mask by appending them to the list of command line arguments. This is useful when the network configuration of the corresponding tap interface is not known at build time, for example when running in a container. When one or more values for the keys `-ip`, `-gateway` and `-mask` are specified, they are provided to the application as environment variables. This way, the hermit-sys network code can read these variables and configure the network device accordingly (see https://github.com/hermitcore/rusty-hermit/pull/204).
> Allow for specifying static network configuration at launch

- src/lib.rs
- src/logging.rs
- src/macros.rs
- src/syscalls/fs.rs
- src/syscalls/mod.rs
- src/syscalls/random.rs
- src/syscalls/tasks.rs
- src/syscalls/timer.rs
Unfortunately macros can't have a path-based scope without being exported from the crate, so we'll have to resort to textual scope.
> Reduce crate exports

- .github/workflows/x86.yml
- .gitlab-ci.yml
- src/arch/x86_64/kernel/acpi.rs
- src/arch/x86_64/kernel/processor.rs
- src/lib.rs
- src/runtime_glue.rs
- src/syscalls/mod.rs
This fixes panicking (exiting in general) before syscalls::init. 
This should fix CI timeouts on early kernel panics.
> Implement early shutdown

- src/lib.rs
https://github.com/hermitcore/libhermit-rs/pull/387 has been merged incorrectly in https://github.com/hermitcore/libhermit-rs/pull/387/commits/6c2d63e6a55e6323a6eec4ff40dabe6c4a6495a6.
> Export errno module

- .cargo/config.toml
- .github/workflows/aarch64.yml
- .github/workflows/doc.yml
- .gitlab-ci.yml
- Cargo.toml
- README.md
- targets/aarch64-unknown-none-hermitkernel.json
- targets/x86_64-unknown-none-hermitkernel.json
Closes https://github.com/hermitcore/rusty-hermit/issues/197#issuecomment-1076416891.
This puts our kernel targets into json files. This is now possible since we do not distribute the kernel via crates.io anymore.
> Use custom targets for kernel

- targets/x86_64-unknown-none-hermitkernel.json
The only remaining difference is the llvm-target.
> Align x86_64 target to x86_64-unknown-none

- Dockerfile
- rust-toolchain.toml
- src/arch/x86_64/kernel/idt.rs
- src/lib.rs
This is the first nightly to not include the hermitkernel targets.
> Update toolchain to 2022-03-27

- targets/aarch64-unknown-none-hermitkernel.json
This removes custom pre-link-args.
> Align aarch64 target to aarch64-unknown-none-softfloat

- Cargo.toml
- src/arch/x86_64/kernel/pci.rs
Supersedes https://github.com/hermitcore/libhermit-rs/pull/155.
This reduces size of the resulting hello-world application from 4.13 MB to 1.04 MB if the pci-ids database is not included.
> Make pci-ids optional

- .github/workflows/aarch64.yml
- .github/workflows/clippy.yml
- .github/workflows/doc.yml
- .github/workflows/format.yml
- .github/workflows/x86.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- targets/aarch64-unknown-none-hermitkernel.json
- targets/x86_64-unknown-none-hermitkernel.json
As discussed in https://github.com/hermitcore/rusty-hermit/issues/197#issuecomment-999379314, this way the kernel's `libhermit.a` has `OS/ABI: UNIX - System V` and the resulting application has `OS/ABI: <unknown: ff>`. This works for the Rust-toolchain as well as the C-toolchain.
> Targets: Use none-elf instead of hermit llvm-target

- src/syscalls/condvar.rs
They are declared in hermit-abi as extern "C" already.
So the current definition without extern "C" is wrong.
> Condvar: Mark sys functions as extern "C"

- Dockerfile
- rust-toolchain.toml
- xtask/src/main.rs
Closes https://github.com/hermitcore/libhermit-rs/issues/412.
This reduces initial build times of the kernel, since `core` and `alloc` are now downloaded instead of compiled ourselves. `x86_64-unknown-none` is tier 2 and ships artifacts, so we can omit `build-std`.
> Migrate to x86_64-unknown-none

- src/arch/x86_64/kernel/mod.rs
They don't seem to be used anywhere and are problematic for C-ABI.
> Remove unused sys_uhyve_* functions

- Cargo.lock
- Cargo.toml
- src/drivers/net/rtl8139.rs
The device driver RTL8139 tries to avoid unneeded copies of buffers. But in case, the ring buffer wrap around, two pieces have to copy into one continuous memory region.
=> temporary creation of a boxed buffers
> RTL8139: Improvement of the ring buffer management

- src/arch/x86_64/kernel/mod.rs
- src/lib.rs
- src/macros.rs
- xtask/src/main.rs
This PR enables lwIP support by using lwIP's rtl8139 driver instead of the kernel implementation.
To workaround https://github.com/hermitcore/libhermit-rs/issues/471, this disables kernel stack switching with newlib. A proper fix would require much more work and insight into our lwIP implementation.
> Enable lwIP support

- src/arch/x86_64/kernel/apic.rs
- src/drivers/net/mod.rs
- src/drivers/net/rtl8139.rs
- src/drivers/net/virtio_net.rs
- src/syscalls/interfaces/mod.rs
- src/syscalls/mod.rs
the new syscall allows us to handle the network interrupt on the core, where the network thread (see hermit-sys) is running
> add option to assign a task to the nic

- src/arch/aarch64/kernel/mod.rs
- src/arch/x86_64/kernel/apic.rs
- src/arch/x86_64/kernel/mod.rs
- src/lib.rs
Closes https://github.com/hermitcore/libhermit-rs/issues/506.
This requires uhyve 0.1.3 to work correctly, but is backwards compatible to the racy uhyve version.
> Correctly sync all cores

- .github/workflows/x86.yml
- src/arch/x86_64/kernel/mod.rs
Closes https://github.com/hermitcore/libhermit-rs/issues/515.
Depends on https://github.com/hermitcore/rusty-loader/pull/148 until https://github.com/hermitcore/libhermit-rs/issues/516 is fixed.
> Fix integration tests

- src/scheduler/task.rs
- src/synch/futex.rs
If a spurious wakeup occurs, the task was removed unconditionally from the queue, meaning it would never be woken. This is fixed if the task is only removed if a timeout occurred.
> Fix deadlock on spurious wakeup in `futex_wait`

- src/env.rs
- src/net/device.rs
- src/syscalls/interfaces/mod.rs
Restores the ability to set the network IP address, gateway and subnet mask via the kernel commandline arguments `-ip`, `-gateway` and `-mask`.
Closes #522
> Restore network configuration via kernel cli

- Cargo.lock
Updating futures-core v0.3.24 -> v0.3.25
Updating getrandom v0.2.7 -> v0.2.8
Updating libc v0.2.135 -> v0.2.137
Updating ppv-lite86 v0.2.16 -> v0.2.17
Updating syn v1.0.102 -> v1.0.103
I am aware that there is a dependabot configuration for keeping such stuff up to date, but it looks like some stuff (e. g. `getrandom` or `ppv-lite`) does not get picked up by dependabot.
> update lockfile / dependencies

- src/scheduler/mod.rs
Closes https://github.com/hermitcore/libhermit-rs/issues/606.
> Make scheduler sharing safe

- Cargo.lock
- Cargo.toml
- src/arch/aarch64/kernel/processor.rs
- src/arch/x86_64/kernel/processor.rs
- src/entropy.rs
- src/lib.rs
- src/macros.rs
- src/syscalls/entropy.rs
- src/syscalls/mod.rs
Fixes #143 by reimplementing random data generation using a [ChaCha-based RNG](https://docs.rs/rand_chacha/0.3.1/rand_chacha/struct.ChaCha20Rng.html) continuously reseeded using the `RDSEED` instruction. This should provide better security, as `RDRAND` is known to have hardware bugs. 
Also adds a new buffer-based syscall, `read_entropy`, which better fits the usecase of crates like [`getrandom`](https://github.com/rust-random/getrandom).
The old `secure_rand*` and `rand` syscalls should probably be removed at some point, but I do not know the Hermit stability policy and therefore have not done this in this PR.
> Reimplement random data generation, add `read_entropy` syscall

- Cargo.lock
- Cargo.toml
- src/arch/x86_64/kernel/apic.rs
- src/arch/x86_64/kernel/scheduler.rs
- src/drivers/net/mod.rs
- src/drivers/net/rtl8139.rs
- src/drivers/net/virtio_mmio.rs
- src/drivers/net/virtio_net.rs
- src/drivers/net/virtio_pci.rs
- src/fd/file.rs
- src/fd/mod.rs
- src/fd/socket/mod.rs
- src/fd/socket/tcp.rs
- src/fd/socket/udp.rs
- src/fd/stdio.rs
- src/net/device.rs
- src/net/executor.rs
- src/net/mod.rs
- src/scheduler/mod.rs
- src/scheduler/task.rs
- src/synch/mod.rs
- src/synch/rwlock.rs
- src/syscalls/interfaces/mod.rs
- src/syscalls/mod.rs
- src/syscalls/net.rs
This PR realize a classical BSD socket layer. To realize a BSD socket layer, the executor has to return directly UNIX-like error number because the layer depends on a C interface and doesn't support Rust's error handling.
> add BSD socket layer

- src/lib.rs
However, in case of newlib the network should not initialize because newlib has its own network stack.
> allow the parallel usage of the features pci and newlib

- src/fd/mod.rs
- for the C user space is the workaround not required
> use workaround only for RustHermit

- src/lib.rs
- src/syscalls/mod.rs
Fixes issue #670.
I removed the shutdown function in src/syscalls/mod.rs as a previous issue #384 had one of the commits implementing early shutdown which was that shutdown function in that particular file. I also removed instances when that shutdown was called, which was in the panic handler, in src/lib.rs, and replaced the shutdown syscall call with crate::__sys_shutdown(1).
> removed all instances of shutdown

- src/arch/x86_64/kernel/gdt.rs
- src/arch/x86_64/kernel/scheduler.rs
- src/scheduler/mod.rs
IST0 isn't used by common interrupt. Just to close the session.
=> don't create IST0 for every task, just for every core
> remove obsolete ist0 handling

- Cargo.lock
- src/arch/x86_64/kernel/apic.rs
- src/arch/x86_64/kernel/gdt.rs
- src/arch/x86_64/kernel/interrupts.rs
- src/arch/x86_64/kernel/pic.rs
- src/arch/x86_64/kernel/processor.rs
- src/arch/x86_64/kernel/scheduler.rs
- src/arch/x86_64/kernel/start.rs
- src/config.rs
- src/scheduler/mod.rs
- this guarantees that we don't toch the red zone
- increase default stack size, which is required to build random numbers with rand_chacha
> use isolated stacks for interrupt handling

- src/fd/mod.rs
- since rust-lang/rust#109368 the workaround isn't longer required
> remove workaround, which fix wrong file flags

- .github/workflows/ci.yml
CI use the latest published loader for aarch64. An initrd is used to test the application.
> CI downloads loader for aarch64

- Cargo.lock
- Dockerfile
- src/arch/x86_64/kernel/mod.rs
- src/arch/x86_64/kernel/processor.rs
- src/arch/x86_64/kernel/systemtime.rs
In case of Firecracker, RustyHermit has to emulate the boot process of Linux. Consequently, rusty-loader forwards the Linux boot params to RustyHermit.
This PR requires hermitcore/hermit-entry#12 and hermitcore/rusty-loader#200.
> add support to boot RustyHermit on Firecracker

- src/arch/x86_64/kernel/core_local.rs
Addresses #686
Add the `repr(C)` layout specifier to the CoreLocal struct.
> Make CoreLocal repr(C)

- src/scheduler/task.rs
Fixes https://github.com/hermitcore/libhermit-rs/issues/377.
> Implements PriorityTaskQueue with std's LinkedList rather than a custom linked list implementation

- Cargo.lock
- Cargo.toml
- src/drivers/net/virtio_net.rs
- src/drivers/virtio/virtqueue/mod.rs
Changed VirtioNetHdr to derive from AsBytes instead of AsSliceU8 and changed related functions as necessary.
> virtio-net: Replace AsSliceU8 trait with zerocopy::AsBytes.

- src/syscalls/fs.rs
- src/syscalls/semaphore.rs
- src/syscalls/timer.rs
Helping with issue #353
Added _(very)_ basic documentation to syscalls in [`timer.rs`](https://github.com/hermitcore/libhermit-rs/blob/master/src/syscalls/timer.rs) and [`semaphore.rs`](https://github.com/hermitcore/libhermit-rs/blob/master/src/syscalls/semaphore.rs)
I used Linux man pages as a reference when writing these.
> Add basic docs for timer and semaphore syscalls

- src/scheduler/mod.rs
- src/scheduler/task.rs
- simplifies the run function of the scheduler
- avoids unneeded calls of the function `schedule`
> add check if the idle task has to give up the processor

- src/arch/x86_64/kernel/apic.rs
uhyve doesn't support a common IO-APIC. Consequently, libhermit should not initialize the IO-APIC
> don't initialize IO-APIC for uhyve

- src/arch/aarch64/mm/virtualmem.rs
On aarch64, the memory region below the kernel can be used for dynamic allocation.
Consequently, the assertion should allow this region.
> revise assertion

- src/arch/aarch64/kernel/scheduler.rs
- src/arch/x86_64/kernel/scheduler.rs
- src/scheduler/task.rs
- ARM used variant 1 of the TLS handling (see https://uclibc.org/docs/tls.pdf)
- the previous version doesn't work correctly
- using an unsized struct to implement TLS like a C kernel
> revise TLS handling

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/arch/aarch64/kernel/interrupts.rs
- src/arch/aarch64/kernel/mod.rs
- src/arch/aarch64/kernel/pci.rs
- src/arch/aarch64/kernel/processor.rs
- src/arch/aarch64/kernel/start.rs
- src/arch/aarch64/kernel/switch.rs
- src/arch/aarch64/kernel/systemtime.rs
- src/arch/aarch64/mm/paging.rs
- src/arch/aarch64/mm/physicalmem.rs
- src/arch/mod.rs
- src/arch/x86_64/kernel/processor.rs
- src/drivers/fs/virtio_pci.rs
- src/drivers/net/rtl8139.rs
- src/drivers/net/virtio_net.rs
- src/drivers/net/virtio_pci.rs
- src/drivers/pci.rs
- src/drivers/virtio/env.rs
- src/drivers/virtio/transport/pci.rs
- src/fd/mod.rs
- src/lib.rs
- src/scheduler/mod.rs
- src/syscalls/interfaces/mod.rs
In case of aarch64, the PCI bar has to program during the initialization. The regions are part of the device trees.
This PR solves also #739 because it enable also the support for virtue-net-pci device for aarch64.
PCI details are available at https://wiki.osdev.org/PCI.
> add option to program the the PCI bars

- .github/workflows/ci.yml
If we don't pin this, we emulate different CPUs on different CPUs. For example, on M2 chips, rusty-loader won't work correctly.
See https://github.com/hermitcore/rusty-loader/pull/228.
> CI (ARM): Pin CPU

- src/drivers/virtio/transport/mmio.rs
- src/drivers/virtio/transport/pci.rs
- src/lib.rs
gurantees that the kernel 16-/32-bit registers to write the data to the device memory
> use write_unaligned to write data to the pci device

- src/arch/aarch64/kernel/interrupts.rs
- src/arch/aarch64/kernel/pci.rs
- src/arch/aarch64/kernel/scheduler.rs
- src/arch/aarch64/kernel/systemtime.rs
- src/arch/aarch64/mm/paging.rs
- src/arch/aarch64/mm/physicalmem.rs
- src/arch/aarch64/mm/virtualmem.rs
- src/arch/x86_64/kernel/acpi.rs
- src/arch/x86_64/kernel/apic.rs
- src/arch/x86_64/kernel/scheduler.rs
- src/arch/x86_64/mm/paging.rs
- src/arch/x86_64/mm/physicalmem.rs
- src/arch/x86_64/mm/virtualmem.rs
- src/lib.rs
- src/mm/mod.rs
- src/scheduler/mod.rs
Related to https://github.com/hermitcore/libhermit-rs/pull/649.
> Format pointer types using Pointer trait

- Cargo.lock
- Cargo.toml
- src/mm/allocator/mod.rs
- src/mm/mod.rs
Closes https://github.com/hermitcore/libhermit-rs/issues/630.
https://github.com/hermitcore/libhermit-rs/pull/803 has even further enhancements, but this might be a first step.
> Migrate to talc memory allocator

- .github/workflows/ci.yml
- Cargo.toml
- src/arch/aarch64/kernel/interrupts.rs
- src/arch/aarch64/kernel/mmio.rs
- src/arch/aarch64/kernel/mod.rs
- src/arch/mod.rs
- src/arch/x86_64/kernel/mmio.rs
- src/arch/x86_64/kernel/mod.rs
- src/arch/x86_64/mm/physicalmem.rs
- src/config.rs
- src/drivers/mmio.rs
- src/drivers/mod.rs
- src/drivers/net/mod.rs
- src/drivers/net/rtl8139.rs
- src/drivers/net/virtio_mmio.rs
- src/drivers/net/virtio_net.rs
- src/drivers/net/virtio_pci.rs
- src/drivers/pci.rs
- src/drivers/virtio/mod.rs
- src/drivers/virtio/transport/mmio.rs
- src/drivers/virtio/transport/pci.rs
- src/env.rs
- src/executor/device.rs
- src/executor/mod.rs
- src/executor/network.rs
- src/fd/socket/tcp.rs
- src/scheduler/mod.rs
- src/scheduler/task.rs
For this purpose, it was necessary to avoid the creation of dynamic objects of the driver. This means that during compilation it must be defined which network interface is used. If the feature `rtl8139` is activated, the driver for Realtek 8139 will be used. Otherwise the Virtio network interface will be used.
> network drivers create directly TxToken / RxToken for smoltcp 

- src/drivers/virtio/transport/mmio.rs
- src/drivers/virtio/transport/pci.rs
Add memory barrier before the device will be notified that new data are available.
> add memory barrier

- src/executor/mod.rs
- src/executor/network.rs
- src/synch/futex.rs
With the previous solution, the "wakeup" may occur before the task is blocked. So that this "wakeup" is not lost, futexes are used. If there is no blocking task available, the value of the futex is changed so that the next task is able to see that a wakeup was already arrived and the task does not have to block.
> using a futex to wakeup network tasks

- src/arch/aarch64/kernel/processor.rs
- src/arch/aarch64/mm/paging.rs
- src/arch/x86_64/mm/paging.rs
- src/mm/mod.rs
`map_heap` can be fail because due to fragmentation it isn't enough continuous memory for 1GB pages available. Consequently, `map_heap` returns as error value the number of sucessfully mapped pages. On success, all requested pages are mapped into the memory.
> fix mapping of 1GB pages

- src/drivers/net/rtl8139.rs
- src/drivers/net/virtio_mmio.rs
- src/drivers/net/virtio_net.rs
- src/drivers/net/virtio_pci.rs
smoltcp uses the Ethernet MTU as definition for the maximum transmission unit. Linux defines MTU as IP MTU. libhermit based on smoltcp and should uses the same definition. Consequently, the default MTU is 1514, which is the default IP MTU (1500) + size of the ethernet header.
> using Ethernet MTU instead IP MTU

- src/drivers/net/mod.rs
- src/drivers/net/virtio_mmio.rs
- src/drivers/net/virtio_net.rs
- src/drivers/net/virtio_pci.rs
- src/executor/device.rs
If the host is able to send packets with partial checksum, the driver will not check these checksums.
> add support of VIRTIO_NET_F_CSUM

- src/drivers/net/virtio_mmio.rs
- src/drivers/net/virtio_pci.rs
Consequently, the same definition like smoltcp is used.
> uses Ehernet MTU as definition of HERMIT_MTU

- src/drivers/net/virtio_net.rs
- src/drivers/virtio/virtqueue/split.rs
- src/fd/socket/tcp.rs
VIRTIO_NET_F_MRG_RXBUF offers the option to merge RX buffers
> add support of VIRTIO_NET_F_MRG_RXBUF

- .github/workflows/ci.yml
- src/arch/aarch64/kernel/mod.rs
- src/arch/x86_64/kernel/mod.rs
- src/lib.rs
- src/macros.rs
GitHub-Closes: https://github.com/hermitcore/libhermit-rs/issues/855
> fix: support lib tests on Apple Silicon

- src/fd/socket/tcp.rs
If smoltcp receives a FIN message, the socket changes the state to the `closing`, but the socket is still active. To close the socket, the kernel returns a error if the socket is in the closing state.
The PR should solve issue hermit-os/kernel#880
> return error also in the closing state

- Cargo.toml
- src/arch/aarch64/kernel/mod.rs
- src/arch/mod.rs
- src/arch/x86_64/kernel/mod.rs
- src/config.rs
- src/drivers/mmio.rs
- src/drivers/mod.rs
- src/drivers/pci.rs
- src/drivers/virtio/mod.rs
- src/drivers/virtio/transport/mmio.rs
- src/drivers/virtio/transport/pci.rs
- src/executor/mod.rs
- src/executor/network.rs
- src/fd/mod.rs
- src/fd/socket/mod.rs
- src/fd/socket/udp.rs
- src/scheduler/mod.rs
- src/scheduler/task.rs
- src/syscalls/mod.rs
In addition, the feature `udp` is added to enable/disable UDP support. The UDP support is only tested by the example `testudp` of hermit-rs.
This PR includes also #881.
> add basic UDP support

- .github/workflows/ci.yml
This creates the cache for pull requests and merge groups.
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
> ci: run on main branch too to create caches

- .github/workflows/ci.yml
- Cargo.lock
Closes https://github.com/hermit-os/kernel/issues/846
This should fix deadlocks by updating hermit-sync to 0.1.4 (https://github.com/hermit-os/hermit-sync/pull/16).
> fix(aarch64): properly disable interrupts on mutexes

- .github/workflows/ci.yml
- fc-config.json
Closes https://github.com/hermit-os/kernel/pull/868
> add KVM tests with uhyve, qemu and firecracker

- src/arch/aarch64/kernel/core_local.rs
- src/arch/x86_64/kernel/apic.rs
- src/arch/x86_64/kernel/core_local.rs
- src/arch/x86_64/kernel/scheduler.rs
- src/drivers/net/mod.rs
- src/executor/network.rs
- src/lib.rs
- src/scheduler/mod.rs
- src/scheduler/task.rs
- src/synch/futex.rs
- src/synch/recmutex.rs
- src/synch/semaphore.rs
- src/syscalls/tasks.rs
Fixes https://github.com/hermit-os/kernel/issues/622
> Make `core_scheduler` sound

- src/errno.rs
- src/fd/file.rs
- src/fd/mod.rs
- src/fs/fuse.rs
- src/lib.rs
- src/syscalls/fs.rs
- src/syscalls/interfaces/mod.rs
- src/syscalls/mod.rs
We added a few new system calls (mkdir, rmdir, lstat, fstat, opendir, readdir) and also modified the stat system call.
Rebase and replace #811
> Extend the FUSE support

- Cargo.lock
- Cargo.toml
- src/arch/aarch64/kernel/core_local.rs
- src/arch/x86_64/kernel/apic.rs
- src/arch/x86_64/kernel/core_local.rs
- src/scheduler/mod.rs
- src/synch/futex.rs
- src/synch/recmutex.rs
- src/synch/semaphore.rs
- src/syscalls/tasks.rs
This
- updates Cargo.lock,
- reverts 8cbf7f6, as this is not ready for a release yet,
- and bumps the version to 0.6.5.
> chore: release version 0.6.5

- src/executor/network.rs
- src/fd/socket/tcp.rs
Previously, network buffers were never deallocated again, resulting in quick out-of-memory situations if many connections are created.
Closes https://github.com/hermit-os/kernel/issues/899
> fix(net): deallocate network buffers

- .github/workflows/ci.yml
Use a test configuration matrix to increase architecture testing parity, decrease CI configuration duplication and run tests at parallel, at the cost of increased compute and storage usage.
> ci: use a matrix for test configurations

- .github/workflows/ci.yml
We currently have only one cache for the whole matrix. Which one is saved is random.
This PR
1. adds more workspaces to the cache
2. creates one cache per arch and profile
3. only saves the cache on `rusty_demo`
CC: @cagatay-y
> ci: improve caches

- src/arch/aarch64/kernel/interrupts.rs
- src/arch/aarch64/kernel/mod.rs
- src/arch/aarch64/kernel/pci.rs
- src/arch/aarch64/kernel/processor.rs
- src/arch/aarch64/kernel/serial.rs
- src/arch/aarch64/kernel/switch.rs
- src/arch/aarch64/kernel/systemtime.rs
- src/arch/aarch64/mm/paging.rs
- src/arch/x86_64/kernel/acpi.rs
- src/arch/x86_64/kernel/apic.rs
- src/arch/x86_64/kernel/mmio.rs
- src/arch/x86_64/kernel/processor.rs
- src/arch/x86_64/kernel/scheduler.rs
- src/arch/x86_64/kernel/switch.rs
- src/drivers/net/virtio_mmio.rs
- src/drivers/virtio/transport/mmio.rs
- src/drivers/virtio/transport/pci.rs
- src/drivers/virtio/virtqueue/mod.rs
- src/drivers/virtio/virtqueue/packed.rs
- src/drivers/virtio/virtqueue/split.rs
- src/fd/mod.rs
- src/lib.rs
- src/mm/allocator.rs
- src/mm/freelist.rs
- src/scheduler/mod.rs
- src/syscalls/condvar.rs
- src/syscalls/interfaces/uhyve.rs
Minimize casts to pointers by using:
- pointer formatting,
- from_exposed_addr{,_mut},
- from_{ref,mut} (solves #793),
- as_str
- and some other methods.
> Minimize casts to pointers

- src/arch/x86_64/kernel/mmio.rs
- src/drivers/net/virtio_net.rs
- src/env.rs
- src/mm/mod.rs
Firecracker pass the configuration of all mmio device by a Linux kernel parameter This parameter is defined as followd:
> virtio_mmio.device=
>    [VMMIO] Memory mapped virtio (platform) device.
> 
>       <size>@<baseaddr>:<irq>[:<id>]
>    where:
>       <size>     := size (can use standard suffixes like K, M and G)
>       <baseaddr> := physical base address
>       <irq>      := interrupt number (as passed to request_irq())
>       <id>       := (optional) platform device id
>    example:
>                  virtio_mmio.device=1K@0x100b0000:48:7
>    Can be used multiple times for multiple devices.
This patch parse the command line and store the string `<size>@<baseaddr>:<irq>[:<id>]` in a vector, which is part of CLI. The vector is used to find the network device on a microVM.
In …
> collect configuration of mmio devices

- .github/workflows/ci.yml
Revert https://github.com/hermit-os/kernel/commit/d541b68479c934d1404de9ce4bf4f648c4c34255
> ci: use latest Firecracker after 1.5.1 release

- hermit-builtins/Cargo.toml
This fixes compilation inside workspaces without explicit exclude.
Closes https://github.com/hermit-os/hermit-rs/issues/511
> feat: make hermit-builtins a workspace root

- src/fd/mod.rs
- src/fd/socket/mod.rs
- src/fd/socket/tcp.rs
- src/fd/socket/udp.rs
- src/syscalls/net.rs
This is an extension of the kernel interface to solve issue hermit-os/kernel#967. The PR was tested with hermit-os/hermit-rs#513
Closes https://github.com/hermit-os/kernel/issues/967
> add recvfrom and sendto support

- Cargo.toml
- src/macros.rs
The feature currently has no meaning. "common-os" will later enable a classical monolithic kernel.
> rename the feature "syscall" to "common-os"

- src/arch/aarch64/kernel/processor.rs
- src/arch/riscv64/kernel/processor.rs
- src/arch/x86_64/kernel/processor.rs
- src/arch/x86_64/mm/paging.rs
- src/syscalls/interfaces/mod.rs
- src/syscalls/interfaces/uhyve.rs
- xtask/src/ci/qemu.rs
If semihosting or qemu_exit is available, the error code will be forwarded to the host system.
> forward error code to the host

- Cargo.lock
- Cargo.toml
- src/console.rs
- src/executor/mod.rs
- src/executor/network.rs
- src/fd/mod.rs
- src/fd/socket/tcp.rs
- src/fd/socket/udp.rs
- src/fd/stdio.rs
- src/fs/fuse.rs
- src/fs/mem.rs
- src/fs/uhyve.rs
- src/lib.rs
- src/macros.rs
- src/syscalls/mod.rs
- src/syscalls/net.rs
`poll()` examines a set of file descriptors to see if some of them are ready for I/O or if certain events have occurred on them. The currenty implementation is using an asynchronous function to check all file descriptors.
This PR should solve smol-rs/polling#177
Currently, the PR doesn't support file descriptors, which points to the uhyve file system.
> add support of a unix-like poll function

- src/arch/x86_64/kernel/mod.rs
- src/arch/x86_64/kernel/serial.rs
- src/executor/mod.rs
- src/fd/eventfd.rs
- src/fd/mod.rs
- src/fd/socket/tcp.rs
- src/fd/socket/udp.rs
- src/fd/stdio.rs
- src/fs/mem.rs
- src/syscalls/mod.rs
- src/syscalls/net.rs
`eventfd` creates an linux-like "eventfd object" that can be used as an event wait/notify mechanism by user-space applications, and by the kernel to notify user-space applications of events. The object contains an unsigned 64-bit integer counter that is maintained by the kernel. This counter is initialized with the value specified in the argument `initval`.
As its return value, `eventfd` returns a new file descriptor that can be used to refer to the eventfd object.
The following values may be bitwise set in flags to change the behavior of `eventfd`:
- `EFD_NONBLOCK`: Set the file descriptor in non-blocking mode
- `EFD_SEMAPHORE`: Provide semaphore-like semantics for reads from the new file descriptor.
In addition, the PR includes some fine-tuning of the IP stack and the behavior of the …
> add basic support a linux-like syscall `evendfd`

- src/env.rs
A kernel panic is too hard. A warning is enough to inform the user.
> ignore unsupported kernel flags

- src/drivers/fs/virtio_fs.rs
- src/drivers/fs/virtio_pci.rs
- src/drivers/virtio/virtqueue/mod.rs
- src/fs/fuse.rs
- src/scheduler/mod.rs
Instead of copying the commands into Virtqueue buffers and the buffers back into responses, directly provide the commands and responses as references to the send_command method.
> fuse: reduce copying and handle errors

- Cargo.lock
- Cargo.toml
- src/arch/aarch64/kernel/serial.rs
- src/arch/x86_64/kernel/interrupts.rs
- src/arch/x86_64/kernel/mod.rs
- src/arch/x86_64/kernel/serial.rs
- src/lib.rs
- src/shell.rs
Currently, the shell is only able to print the number of received interrupts. Type `h` to show the supported commands.
> add option to start a simple shell as async task

- src/fs/fuse.rs
Closes https://github.com/hermit-os/kernel/issues/1110.
> fix(fuse): fix fat pointer metadata

- src/fs/fuse.rs
FUSE seems to expect in the length field of the header the total length of the command without the padding. This PR fixes #1111.
> fuse: fix incorrect len field in command headers

- src/fs/uhyve.rs
Currently, Uhyve mounts to `/host` and virtiofsd mounts to `/root` (see [rftrace-example](https://github.com/hermit-os/hermit-rs/blob/14b59f8e92d9981446448003ff13ef6cc6469f56/examples/rftrace-example/src/main.rs#L12)).
Both [`xtask`](https://github.com/hermit-os/kernel/blob/6a89761bdc2dbdac6a3843079aed8579a9d3f8e7/xtask/src/ci/qemu.rs#L251) and [`runh`](https://github.com/hermit-os/runh/blob/70663eacd81f159b9a8bb107fe058f58b8b5ace0/src/hermit.rs#L115) currently set `tag=root` for virtiosfsd.
> feat: align Uhyve mount path to virtiofsd

- Cargo.lock
- Cargo.toml
- src/arch/riscv64/kernel/mod.rs
- src/arch/riscv64/kernel/processor.rs
The SBI legacy extensions are deprecated 4 years ago ( https://github.com/riscv-non-isa/riscv-sbi-doc/commit/705e9556d25dc070926b99f8ccbcdc5073407447 ). We replace it using functions from SBI 2.0 extensions. Specifically:
- the legacy console_putchar is replaced into console_write_byte in SBI DBCN extension;
- legacy shutdown is replaced to system_reset in SBI SRST extension with ColdReboot and NoReason as parameters;
- legacy set_timer is replaced with SBI TIME set_timer;
- legacy send_ipi is replaced to SBI IPI extension. The code implemented in file processor.rs creates a HartMask with only one hart_id selected as an IPI target.
By updating to SBI 2.0, this commit supports to send IPI to hart IDs greater than 63 (on 64-bit devices). The current code encodes hart_id parameter in …
> riscv64: replace deprecated legacy extensions to SBI 2.0 extensions

- src/drivers/virtio/transport/pci.rs
This is another workaround for https://github.com/hermit-os/kernel/issues/199 to unblock these PRs:
- https://github.com/hermit-os/kernel/pull/1045
- https://github.com/hermit-os/kernel/pull/1126
- https://github.com/hermit-os/kernel/pull/1141
> fix(virtio/pci): use volatile accesses for device features

- rust-toolchain.toml
- src/arch/aarch64/kernel/interrupts.rs
- src/arch/aarch64/kernel/mod.rs
- src/arch/aarch64/kernel/pci.rs
- src/arch/aarch64/kernel/processor.rs
- src/arch/aarch64/kernel/scheduler.rs
- src/arch/aarch64/kernel/serial.rs
- src/arch/aarch64/kernel/systemtime.rs
- src/arch/aarch64/mm/paging.rs
- src/arch/riscv64/mm/paging.rs
- src/arch/x86_64/kernel/acpi.rs
- src/arch/x86_64/kernel/apic.rs
- src/arch/x86_64/kernel/mmio.rs
- src/arch/x86_64/kernel/pci.rs
- src/arch/x86_64/kernel/processor.rs
- src/arch/x86_64/kernel/scheduler.rs
- src/arch/x86_64/mm/paging.rs
- src/drivers/net/virtio_mmio.rs
- src/drivers/virtio/transport/mmio.rs
- src/drivers/virtio/transport/pci.rs
- src/drivers/virtio/virtqueue/mod.rs
- src/drivers/virtio/virtqueue/packed.rs
- src/drivers/virtio/virtqueue/split.rs
- src/fs/fuse.rs
- src/lib.rs
- src/syscalls/condvar.rs
- src/syscalls/interfaces/uhyve.rs
- src/syscalls/tasks.rs
In addition, this PR rename ptr::from_exposed_addr to ptr::with_exposed_provenance, which is required by rust-lang/rust#122935
> chore: upgrade to nightly-2024-04-15

- src/drivers/virtio/virtqueue/packed.rs
- src/drivers/virtio/virtqueue/split.rs
The Virtio specification specifies little-endian as the correct endianness for its structs. Although it matches the native endianness of the platforms we support, this change allows us to match the specification explicitly.
> virtq: specify endianness

- Cargo.lock
- Cargo.toml
- src/drivers/virtio/transport/pci.rs
Related to https://github.com/hermit-os/kernel/issues/199
> fix(virtio/pci): put common config into volatile reference

- src/arch/aarch64/kernel/scheduler.rs
Before, we were allocating not enough memory for `TaskTLS`, resulting in memory corruption once we remove the memory overprovisioning in https://github.com/hermit-os/kernel/pull/1045.
> fix(aarch64): add size of `_private` to `TaskTLS` allocation

- src/mm/allocator.rs
Thought I'd check up on how people were using talc in the wild :)
There are two ideas here:
1. Use `talc`'s reallocation mechanisms. This is recommended for faster in-place reallocation (avoiding the much-more-expensive memcpy that default-reallocation _always_ invokes) and also allows for interleaving some allocator operations as introduced in v4.2 to somewhat improve allocation concurrency.
2. Avoid padding the size of allocations. Increasing the alignment of an allocation is sufficient to avoid false sharing. Talc needs a little bit of metadata next to each allocation, and this would create `N-8` sized holes in between every allocation due to the demands placed on it. By removing the size requirement, false sharing avoidance is unhindered, but this allows Talc to minimize the overhead …
> perf: forward default allocator methods and remove memory overprovisioning

- src/arch/x86_64/kernel/mmio.rs
- src/drivers/virtio/transport/mmio.rs
This fixes `virtio-net-device` (MMIO) detection and initialization.
> fix(x86_64): virtio-net-device (MMIO)

- Cargo.lock
- Cargo.toml
- src/logging.rs
Closes #905 
Also see https://github.com/hermit-os/loader/pull/336
> new: Add colored log levels

- src/errno.rs
- src/scheduler/mod.rs
- src/scheduler/task.rs
- src/syscalls/mod.rs
- src/syscalls/semaphore.rs
- src/syscalls/socket.rs
- src/syscalls/tasks.rs
- src/syscalls/timer.rs
- src/time.rs
In case, that POSIX provides similar system calls, HermitOS uses variants of these system calls. These similiarties should increase the readability of the interface.
See also hermit-os/hermit-rs#570
> feat: stabilize kernel interface

- Cargo.toml
- src/drivers/virtio/virtqueue/mod.rs
- src/drivers/virtio/virtqueue/split.rs
- src/lib.rs
The code is not ready as I haven't yet figured out how the existing code ensures that the whole allocation is on the same page. This PR needs to be modified to ensure that as well. It is also based on #1141.
> virtq: use a struct with the actual layout rather than a struct of references

- src/syscalls/processor.rs
We could deprecate `sys_get_processor_count` in favor of `sys_available_parallelism`.
> feat(sys): add `sys_available_parallelism`

- src/fs/fuse.rs
- src/fs/mem.rs
- src/fs/mod.rs
- src/syscalls/futex.rs
- src/syscalls/timer.rs
- src/time.rs
This also improves handling of dates before UNIX epoch.
> fix(POSIX/time): make subsecond fields signed and use `timespec` in `stat`

- .github/workflows/ci.yml
- src/arch/x86_64/kernel/mmio.rs
- src/drivers/virtio/transport/mmio.rs
- src/drivers/virtio/transport/pci.rs
- src/drivers/virtio/virtqueue/split.rs
- xtask/src/ci/qemu.rs
Fix the initialize of the MMIO device and use the correct interrupt number. In addition, the driver writes always 32bit values to the MMIO device. Otherwise, the device will not see the device notification.
Closes #1173
> Fix device notification

- src/fd/socket/tcp.rs
- src/syscalls/socket.rs
IpAddress::Ipv4 contains alreads the IP address in big-endian formt. => no byte swapping needed
With these changes, the demo httpd shows the correct address of the client.
> fix conversion from IpAddress::Ipv4 to in_addr

- src/fd/mod.rs
- src/fs/fuse.rs
- src/fs/mem.rs
Similar to Linux, a directory can be opened. The file descriptor can be used to read the directory entries.
> add option to open a directory

- src/syscalls/mod.rs
the offers the possibility to read or to write data into multiple buffers
See https://github.com/hermit-os/hermit-rs/pull/580.
> add system calls `readv` and `writev`

- src/drivers/fs/virtio_fs.rs
- src/drivers/virtio/virtqueue/mod.rs
- src/drivers/virtio/virtqueue/packed.rs
- src/drivers/virtio/virtqueue/split.rs
- src/fd/mod.rs
- src/fs/fuse.rs
Providing headers and payloads separately allows us to avoid the complexity associated with dynamically-sized types and in some cases copying.
> fuse: provide header and payloads separately

- src/executor/device.rs
Per default, Hermit's (static) network interface uses 9.9.9.9 (Quad9) and 1.1.1.1 (Cloudflare) as DNS servers. The default configuration could be overloaded at compile time by the environment variables HERMIT_DNS1 and HERMIT_DNS2. For instance, the following command sets the DNS servers to 8.8.8.8 and 8.8.4.4 .
```
HERMIT_DNS1="8.8.8.8" HERMIT_DNS2="8.8.4.4" cargo build -Z build-std=std,core,alloc,panic_abort --target x86_64-unknown-hermit --features hermit/dns,hermit/tcp
```
> add option to define the DNS servers at compile time

- src/fs/mod.rs
- return return instead a Result
> remove unneeded unwraps

- .github/workflows/ci.yml
@stlankes, CI broke after `v0.8.x` got updated from https://github.com/hermit-os/mio/commit/f5d912e774a9b24767cc937c8e3a1be9f8253334 to https://github.com/hermit-os/mio/commit/a8a5c5bbcf5590901ff41d76ed1ee60464f33f54.
See https://github.com/hermit-os/kernel/actions/runs/9242628556/job/25489845418.
> ci: workaround bad mio branch

- src/fs/fuse.rs
There has been a panic here at least once: https://github.com/hermit-os/kernel/actions/runs/9357240494/job/25756534015?pr=1248#step:25:195
```
$ cargo xtask ci qemu --arch x86_64 --profile release --package rftrace-example --virtiofsd
...
Saving traces to disk...!
0xc1b000, Events { ptr: 0xc1b000, len: 2000, cap: 2000 }
Parsing TID 1...!
Writing to disk: 8 events, 128 bytes (/root/tracedir/1.dat)
Parsed all events!
Creating fake uftrace data dir at /root/tracedir..
Creating ./info
feats = TASK_SESSION | SYM_REL_ADDR
info = CMDLINE | TASKINFO
cmdline = 'fakeuftrace'
tid = [1]
Creating ./task.txt
[0][PANIC] panicked at src/fs/fuse.rs:479:47:
called `Result::unwrap()` on an `Err` value: TryFromIntError(())
```
> fix(fuse): potential panic on unknown mode bits

- src/arch/aarch64/kernel/pci.rs
- src/drivers/net/rtl8139.rs
- src/drivers/net/virtio_pci.rs
- src/drivers/pci.rs
- src/drivers/virtio/transport/pci.rs
This is best reviewed commit by commit.
We can remove `DeviceHeader` fully once https://github.com/rust-osdev/pci_types/pull/21 is released.
> refactor(pci): use more of the `pci_types` crate

- src/drivers/virtio/transport/pci.rs
This was forgotten in https://github.com/hermit-os/kernel/pull/1149.
> fix(virtio/pci): remove `ComCfgRaw`

- Cargo.toml
- src/arch/x86_64/kernel/apic.rs
- src/arch/x86_64/kernel/core_local.rs
- src/arch/x86_64/kernel/interrupts.rs
- src/arch/x86_64/kernel/processor.rs
- src/scheduler/mod.rs
- src/scheduler/task.rs
Instead of the `hlt` instruction, the idle loop use the `pause` instruction. => lower latency to wake up the core, but higher energy consumption.
In addition, this PR support `monitor`/`mwait` instructions. In this, the kernel hasn't to send an IPI to wakeup a core.  The second optimization is that the kernels sends only an IPI, if the core is halted.
> add option to use a busy waiting within the idle loop

- Cargo.lock
- src/drivers/virtio/transport/mmio.rs
- src/drivers/virtio/transport/pci.rs
- src/drivers/virtio/virtqueue/packed.rs
- src/drivers/virtio/virtqueue/split.rs
- virtio-spec/Cargo.toml
- virtio-spec/src/mmio.rs
- virtio-spec/src/pci.rs
Depends on https://github.com/wrenger/bitfield-struct-rs/pull/39.
> refactor(virtio): move `notif_data` into virtio-spec

- .github/workflows/ci.yml
See https://github.com/hermit-os/kernel/issues/1286
> ci: allow deadlocking SMP test on 64-bit RISC-V

- src/drivers/virtio/virtqueue/packed.rs
This was an oversight in [`ed87942`](https://github.com/hermit-os/kernel/commit/ed87942798e44c8d5337b7f03e1ada80f2bb4cfa#diff-07dba9e5c603eb9b9163e081becfabea01d5d932b30f411de671140c446461d7L796-L799).
> fix(virtqueue/packed): set flags according to wrap count

- src/syscalls/interfaces/uhyve.rs
Another one of these "How has this worked before" bugs:
`env` is a vector of pointers where uhyve writes the environment variables into. This vector is then cast into a pointer and passed to `std::sys::pal::hermit::os::init_environment`, where a hashmap is built from this list by iterating over the pointers.
The stop-condition of this iteration is a nullptr, but we never added that to the vector. Probably it worked before because the memory at the end of the list was zero by chance, but it failed now on my machine.
I appreciate any second thoughts because I'm skeptical as the bug has not triggered before.
> Fixed missing NULLPTR at the end of the environment list from uhyve

- Cargo.toml
- src/arch/riscv64/mm/paging.rs
- src/arch/x86_64/mm/paging.rs
- src/syscalls/mmap.rs
- src/syscalls/mod.rs
- src/syscalls/system.rs
Both system calls aren't compatible to POSIX. mmap is only used to map a memory region into the address space.
> add feature to support mmap and munmap

- src/drivers/fs/virtio_fs.rs
- src/drivers/net/virtio/mod.rs
- src/drivers/virtio/virtqueue/mod.rs
- src/drivers/virtio/virtqueue/packed.rs
- src/drivers/virtio/virtqueue/split.rs
TransferTokens carry the control descriptor that represents the indirect descriptor table in them, which is not of the same type for split queues and packed queues. This type difference is currently hidden behind the type erasing MemDescr type, but when we change the structure to use the actual type for it, we will need to make TransferToken generic. An actually typed TransferToken would not work for driver code that decides the type of queue to use at runtime, as we cannot make a boxed slice (which control descriptors represent) work with dynamically-sized elements.
Furthermore, TransferTokens are tied to a particular type of queue, as it would be an error to dispatch a TransferToken that has a control descriptor that is suitable for a PackedVq through a SplitVq. To ensure dispatch …
>  virtq: don't expose TransferTokens to the drivers

- .github/workflows/ci.yml
This reverts commit 786860b156e04c1c1b9a488dfc70fe1e27abd0fe from https://github.com/hermit-os/kernel/pull/1236.
See https://github.com/tokio-rs/mio/pull/1775#issuecomment-2213682804.
> Revert "ci: workaround bad mio branch"

- src/fd/mod.rs
- src/fs/fuse.rs
- src/fs/mem.rs
- src/fs/mod.rs
- src/fs/uhyve.rs
- src/mm/mod.rs
- src/syscalls/mod.rs
In addition, the synchronous `lseek` interface is converted asynchronous interface. Furthermore, if the feature `mmap` is available, the heap is reduced because it will expected that `mmap` will be used to map additional pages into the user address space.
> add lseek support for in-memory files

- Cargo.toml
Per default, IP framentation should be activated to avoid issues like hermit-os/hermit-rs#606
closes hermit-os/hermit-rs#606
> enable IP fragmentation

- src/drivers/virtio/virtqueue/split.rs
The incorrect index was used to iterate over the descriptor chain. Fixes #1327.
> fix(virtq/split): return id with the correct index for the chain head

- src/drivers/fs/virtio_fs.rs
- src/drivers/net/virtio/mmio.rs
- src/drivers/net/virtio/mod.rs
- src/drivers/virtio/virtqueue/mod.rs
- src/drivers/virtio/virtqueue/packed.rs
- src/drivers/virtio/virtqueue/split.rs
Since we no longer store a reference to the queue inside the transfer structures, we don't need to wrap the queues inside `Rc`s and the queue fields inside `RefCell`s.
> refactor(virtq): eliminate RefCell and Rc usage

- src/arch/aarch64/kernel/interrupts.rs
When parsing the Interrupt-Flags from the device-tree, only the 4 least significant bits specify the Trigger-Mode.
(ref: https://elixir.bootlin.com/linux/v6.10.2/source/Documentation/devicetree/bindings/interrupt-controller/arm,gic.yaml).
Only check 4 least significant bits by masking the others to make sure this does not lead to wrong panics.
> Fix: Correctly parse irq-flags from dts

- .github/workflows/ci.yml
- src/arch/aarch64/kernel/mod.rs
- src/arch/mod.rs
- src/arch/riscv64/kernel/mod.rs
- src/arch/x86_64/kernel/apic.rs
- src/arch/x86_64/kernel/mod.rs
- src/lib.rs
Without this, an application processor might call `scheduler::add_current_core` before the boot processor, for example on the GitHub runners with Uhyve.
Fixes https://github.com/hermit-os/kernel/issues/1366
> fix: boot application processors after initializing scheduler

- src/arch/x86_64/mm/paging.rs
This happens every time we spawn and destroy threads.
> fix(x86_64): downgrade log level of page unmap

- src/arch/aarch64/kernel/mod.rs
- src/arch/riscv64/kernel/mod.rs
- src/env.rs
- src/syscalls/interfaces/uhyve.rs
This PR
1. unifies FDT bootargs parsing across all platforms,
2. adds `env=KEY=VALUE` kernel arguments for environment variable initialization, and
3. disables the Uhyve `CMDSIZE` and `CMDVAL` hypercalls to use the kernel-maintained environment on Uhyve (breaking).
1. Should we use the proposed `env=KEY=VALUE` format? This differs from our current format for other kernel arguments, such as `-freq FREQ` and `-ip IP`. I think we should migrate those to `freq=FREQ` and `ip=IP` eventually.
2. Do we need to support `=` in environment variable names?
3. Should we immediately disable the Uhyve hypercalls (easy)? This would break older versions of Uhyve, but I don't think this is a big problem. Alternatively, we could merge the Uhyve hypercall environment with the kernel one (complicated), or we …
> feat(env): parse env=KEY=VALUE for env vars

- Cargo.lock
- Cargo.toml
- src/drivers/net/virtio/mod.rs
- src/drivers/virtio/virtqueue/mod.rs
- src/drivers/virtio/virtqueue/packed.rs
- src/drivers/virtio/virtqueue/split.rs
- src/drivers/vsock/mod.rs
Rather than pushing used buffers from the queues to channels, return them directly to the drivers. This removes the dependency on `async-channel`.
> refactor(virtq): remove intermediate virtqueue channels

- src/drivers/fs/virtio_fs.rs
- src/drivers/fs/virtio_pci.rs
- src/drivers/net/virtio/mod.rs
- src/drivers/net/virtio/pci.rs
- src/drivers/virtio/mod.rs
- src/drivers/virtio/transport/pci.rs
- src/drivers/vsock/pci.rs
According to the section 4.1.4 of the VIRTIO specification v1.2, "[t]he order of the capabilities in the capability list specifies the order of preference suggested by the device." Accordingly, store only the most preferred capability of a type in the `UniCapsCollection` structure when only one is necessary.
This also allows the corresponding fields to be changed from vectors to singles (when appropriate) and the existence of the mandatory capabilities to be checked early on.
> virtio-pci: store only the most preferred capability of a type

- src/arch/aarch64/kernel/interrupts.rs
- src/arch/aarch64/kernel/mod.rs
- src/arch/aarch64/kernel/pci.rs
- src/arch/riscv64/kernel/mmio.rs
- src/arch/riscv64/kernel/mod.rs
- src/arch/riscv64/kernel/processor.rs
- src/arch/x86_64/kernel/mmio.rs
- src/arch/x86_64/kernel/pci.rs
- src/arch/x86_64/kernel/vga.rs
- src/drivers/fs/virtio_fs.rs
- src/drivers/net/gem.rs
- src/drivers/pci.rs
- src/drivers/virtio/transport/mmio.rs
- src/drivers/virtio/transport/pci.rs
- src/drivers/virtio/virtqueue/mod.rs
- src/fs/fuse.rs
- src/init_cell.rs
- src/lib.rs
This resolves the `static_mut_refs` lint by putting offending `static mut`s into cells or mutexes.
> fix: `static_mut_refs`

- .github/workflows/ci.yml
- src/arch/x86_64/kernel/acpi.rs
- src/arch/x86_64/kernel/apic.rs
- src/arch/x86_64/kernel/scheduler.rs
- src/arch/x86_64/mm/paging.rs
- src/arch/x86_64/mm/physicalmem.rs
- src/arch/x86_64/mm/virtualmem.rs
- src/drivers/pci.rs
- src/env.rs
- src/mm/mod.rs
- xtask/src/ci/qemu.rs
Depends on https://github.com/hermit-os/loader/pull/325.
Based on:
- https://github.com/hermit-os/kernel/pull/1278
- https://github.com/hermit-os/kernel/pull/1433
- https://github.com/hermit-os/kernel/pull/1434
- https://github.com/hermit-os/kernel/pull/1435
- https://github.com/hermit-os/kernel/pull/1436
Closes https://github.com/hermit-os/kernel/pull/924
Closes https://github.com/hermit-os/kernel/pull/992
> feat: UEFI MVP

- Cargo.lock
- Cargo.toml
- src/executor/device.rs
- src/executor/mod.rs
- src/executor/network.rs
- src/fd/eventfd.rs
- src/fd/mod.rs
- src/fd/socket/tcp.rs
- src/fd/socket/udp.rs
- src/fd/socket/vsock.rs
- src/fd/stdio.rs
- src/fs/fuse.rs
- src/fs/mem.rs
- src/fs/mod.rs
- src/fs/uhyve.rs
- src/io.rs
- src/scheduler/mod.rs
- src/scheduler/task.rs
- src/syscalls/mod.rs
- src/syscalls/socket.rs
Revise object interface to be a complete asynchronous interface. In addition, add support of listen to increase queue limit for incoming connections.
smoltcp-rs/smoltcp#852 describes if N sockets are listening on the same port, an incoming connections go to a random socket. Consequently, this PR checks all listening sockets to accept a connection.
> add option to increase queue limit for incoming connections

- src/arch/aarch64/kernel/scheduler.rs
- src/arch/riscv64/kernel/scheduler.rs
- src/arch/x86_64/kernel/scheduler.rs
- the stack initialization with dummy values isn't longer necessary
- initialization with 0 reduce the number of "memset" calls
> zeroed stack during the initialization

- src/arch/x86_64/kernel/scheduler.rs
TLS alignment may be 4 and require an unaligned write. This was found with hermit-c and cargo-careful.
> fix(x86_64): use unaligned write for TLS pointer

- xtask/src/ci/uhyve.rs
This is gone since Uhyve 0.4.0.
> fix(xtask): remove `--verbose` from Uhyve call

- .vscode/settings.json
This is required because of https://github.com/hermit-os/kernel/pull/1442.
See also https://github.com/hermit-os/kernel/pull/1451.
CC: @jounathaen
> build(vscode): don't check all architectures

- .github/workflows/ci.yml
Removing caches actually speeds up our CI ([before](https://github.com/hermit-os/kernel/actions/runs/12271864154) vs. [after](https://github.com/hermit-os/kernel/actions/runs/12275289472)):
- Short jobs (`check`, `clippy`, `doc`, `build`, `test`) may be up to 30 seconds slower, but this was mostly variance in QEMU installs.
- For long jobs, the cache does not provide benefits. Due to testing many configurations in one job, things get recompiled anyway.
- We are recently seeing some out-of-disk-space errors. These will hopefully be mended by avoiding a non-clean cache.
> ci: remove caching

- src/arch/x86_64/mm/paging.rs
I'm reworking the initial page mapping of uhyve to resolve https://github.com/hermit-os/uhyve/issues/426, but the kernel currently expects the first GiB to be mapped and panics otherwise. 
In a transition phase, it makes sense to at least not panic if the page is not mapped.
> uhyve: don't panic on initial unmap if page is not mapped

- src/arch/aarch64/kernel/mod.rs
- src/arch/aarch64/kernel/serial.rs
- src/arch/mod.rs
- src/arch/riscv64/kernel/mod.rs
- src/arch/x86_64/kernel/interrupts.rs
- src/arch/x86_64/kernel/mod.rs
- src/arch/x86_64/kernel/serial.rs
- src/console.rs
- src/fd/stdio.rs
- src/lib.rs
- src/macros.rs
- src/shell.rs
- src/syscalls/interfaces/mod.rs
- xtask/src/clippy.rs
Closes https://github.com/hermit-os/kernel/issues/1502.
> feat: rework console and resolve deadlock when panicking while printing

- src/arch/x86_64/mm/virtualmem.rs
- otherwise PageRange::new is able to return an error
> revise the heap size of monolithic version of HermitOS

- src/synch/futex.rs
- src/syscalls/futex.rs
In the `futex_wake` syscall, the address of the passed pointer is used to index a hash map. This pull request removes an unnecessary roundtrip through `&AtomicU32` and thereby make it safe to call `futex_wake` with a dangling pointer. This change enables using `futex_wake` in `parking_lot_core` without additional locking.
> avoid unnecessary dereference in futex_wake

- src/drivers/virtio/virtqueue/mod.rs
Closes https://github.com/hermit-os/kernel/issues/1514.
This was a `usize` before, which got cast to `u32` without checks, which was wrong: [`1749ab4`](https://github.com/hermit-os/kernel/commit/1749ab4e547662c49eacdcd1490b63706de35978#diff-7be7614ab7713c8f3be62447e6a579dbd78b3757c84cd38559566aee623b62d4L1446-L1450)
The fix for that restricted this to `u16`, though, which is too narrow.
`u32` should be correct, though: https://docs.oasis-open.org/virtio/virtio/v1.2/cs01/virtio-v1.2-cs01.html#x1-430005
> fix(virtqueue): make `BufferElem::{len,capacity}` return `u32`

- src/fs/fuse.rs
> implement fstat for fuse file handles via getattr

- src/fs/uhyve.rs
> fix(uhyve): fix improper unlink string handling

- src/executor/device.rs
- src/executor/network.rs
I am not sure on this but rounding up to the next power of two seems sensible to me.
In their [server example](https://github.com/smoltcp-rs/smoltcp/blob/v0.12.0/examples/server.rs), smoltcp uses `0xffff`, but in the [benchmark](https://github.com/smoltcp-rs/smoltcp/blob/v0.12.0/examples/loopback_benchmark.rs) they use `0x10000`.
`0x10000` also aligns with the maximum for the `fragmentation_buffer_size` and `reassembly_buffer_size` configuration options.
> perf: make network buffers a power of two

- Cargo.lock
- Cargo.toml
- src/fs/uhyve.rs
- src/syscalls/interfaces/uhyve.rs
- src/syscalls/mod.rs
This depends on https://github.com/hermit-os/uhyve/pull/757 (and a publication of uhyve interface V0.1.2)
This is the final step of putting the hypercall definitions in a central crate.
This PR should just deduplicate code without changing functionality.
> Use hypercall definitions from uhyve-interface

- src/fs/uhyve.rs
Instead of handling the null terminators ourselves, we relied on the FUSE implementation to store a “prefix” in `UhyveDirectory` and began using `CString`s instead.
This is based on the previous work of Çağatay Yiğit Şahin (https://github.com/hermit-os/kernel/commit/58da42656a910a913605ecac7119a3f0f6c41b35).
> feat(uhyve): use absolute paths

- .github/workflows/ci.yml
Otherwise, Dependabot cannot resolve semantic versions for actions.
> ci: specify `install-action` version

- .github/workflows/security_audit.yml
See https://github.com/rustsec/audit-check/issues/34.
> ci: don't run `security_audit` workflow on PRs

- xtask/src/main.rs
This reverts commit addf9f00ba4560896305949051fdc6bf62b1494a.
> fix(xtask): don't assume exe exists in `cargo_home`

- Cargo.lock
- Cargo.toml
- src/arch/aarch64/kernel/mod.rs
- src/arch/aarch64/kernel/serial.rs
- src/arch/x86_64/kernel/serial.rs
- src/console.rs
- src/syscalls/interfaces/uhyve.rs
- Uhyve: Use the `SerialBufferWrite` hypercall instead of the `Uart` hypercall: This reduces the number of serial output related hypercalls by ~3x.
Attention:
- Depends on https://github.com/hermit-os/kernel/pull/1393
- Depends on a new Uhyve release that has support for this hypercall (v0.4.0)
> Uhyve: Speed up serial output

- src/fs/mem.rs
- src/fs/mod.rs
By using slices instead of raw pointers, the number of unsafe code regions can be reduced.
> remove unsafe code regions

- Cargo.lock
```
Updating bitfield-struct v0.9.3 -> v0.9.5
Updating bumpalo v3.16.0 -> v3.17.0
Updating bytes v1.9.0 -> v1.10.0
Updating cc v1.2.10 -> v1.2.12
Updating clap v4.5.27 -> v4.5.28
Updating clap_derive v4.5.24 -> v4.5.28
Updating cpufeatures v0.2.16 -> v0.2.17
Updating hermit-entry v0.10.2 -> v0.10.3
Updating httparse v1.9.5 -> v1.10.0
Updating rustix v0.38.43 -> v0.38.44
Updating unicode-ident v1.0.14 -> v1.0.16
Updating zerocopy v0.8.14 -> v0.8.16
Updating zerocopy-derive v0.8.14 -> v0.8.16
```
Extracted from https://github.com/hermit-os/kernel/pull/1582.
> build(deps): upgrade `Cargo.lock`

- CITATION.cff
- README.md
Fixes #1226 , superseeds https://github.com/hermit-os/kernel/pull/1478/
- Authors list might need to be extended
- preferred citation is still debated internally
> Added citation instructions and DOI

- src/fd/eventfd.rs
- src/fd/mod.rs
- src/fd/socket/tcp.rs
- src/fd/socket/udp.rs
- src/fd/socket/vsock.rs
- src/fd/stdio.rs
- src/fs/fuse.rs
- src/fs/mem.rs
- src/fs/mod.rs
- src/fs/uhyve.rs
- src/lib.rs
- src/syscalls/mod.rs
- src/syscalls/socket.rs
Currently, when using an uninitialized buffer for `read` or `recvfrom`, as would be typical in C or required for `Read::read_buf`, it is casted from `*mut u8` at the FFI boundary in `sys_read`/`sys_readv`/`sys_recvfrom` to a `&[u8]`. I think this is unsound. Instead, use `&[MaybeUninit<u8>]` internally.
I use `&[u8]` instead of `core::io::BorrowedCursor<'_>`, because there are currently no cases where the initialized portion needs to be separately tracked.
Since `smoltcp::socket::tcp::Socket::recv_slice` takes a `&[u8]`, inline it and refactor. As a bonus, this avoids a copy and clear in the error case and it makes it more clear that packets are dropped when given an insufficiently large buffer.
This PR enables implementing `std::io::Read::read_buf` for `std::fs::File` and …
> Use uninitialized buffers for `read` and `recvfrom`

- src/drivers/mod.rs
- src/lib.rs
Issue found with @marcomaas1990.
> fix(drivers): initialize 64-bit RISC-V drivers before the executor

- src/arch/x86_64/kernel/apic.rs
This trips up our typo tool otherwise.
> style(x86_64/apic): rename typ to ty for types

- src/fs/fuse.rs
- src/fs/mem.rs
- src/fs/mod.rs
> **blkcnt_t** and **off_t** shall be signed integer types.
[<sys/types.h>](https://pubs.opengroup.org/onlinepubs/9799919799/basedefs/sys_types.h.html)
> feat(fs): make `off_t` signed as required by POSIX

- src/fd/mod.rs
- src/fd/socket/tcp.rs
- src/fd/socket/udp.rs
- src/fd/socket/vsock.rs
- src/syscalls/mod.rs
- src/syscalls/socket.rs
This implements `fcntl(F_GETFL)` in three steps:
1. Move file status flags (`O_APPEND` and `O_NONBLOCK`) from `OpenOptions` into a new `fd::StatusFlags` type as per POSIX.
2. Replace `ObjectInterface::ioctl(&self, cmd: IoCtl, value: bool)` with `ObjectInterface::set_status_flags(&self, status_flags: fd::StatusFlags)`, as that seems more straightforward for adding methods compared to adding more values to `IoCtl` and handling those in the implementors.
3. Implement `fcntl(F_GETFL)` by adding `ObjectInterface::status_flags(&self)`.
This closes https://github.com/hermit-os/kernel/issues/1383.
> feat(fd): implement `fcntl(F_GETFL)`

- .github/workflows/ci.yml
- src/arch/riscv64/kernel/interrupts.rs
The function external_eoi() was removed to prevent premature end-of-interrupt (EOI) signaling before the interrupt was fully processed. 
In the previous implementation, external_eoi() was called too early, which could lead to lost or duplicated interrupts.
Additionally, the new implementation reduces redundant lock acquisitions (by external_eoi() and external_handler()) and improves efficiency by consolidating the interrupt handling into a single function. 
This ensures correct processing order and improves system stability, particularly for Virtio-MMIO-based network communication.
> fix(riscv64): improved interrupt_handling with virtio_mmio devices

- src/fs/mem.rs
> O_CREAT: If the file exists, this flag has no effect except as noted under O_EXCL below.
[open](https://pubs.opengroup.org/onlinepubs/9799919799/functions/open.html)
Closes https://github.com/hermit-os/kernel/issues/1641.
> fix(fs): only check for `O_CREAT` if file does not exist

- src/mm/mod.rs
because these types are used by the exported function virtual_to_physical
> export VirtAddr and PhysAddr

- src/arch/x86_64/mm/physicalmem.rs
- print error message instead of unwrapping the result
> avoid panic if deallocation of memory regions failed

- src/arch/aarch64/kernel/interrupts.rs
- src/arch/aarch64/kernel/mod.rs
uhyve doesn't aarch64's performance monitors extensions => avoid initialization
> fix(uhyve): minor changes to disable unsupported feature 

- src/drivers/net/virtio/mod.rs
This is also a required feature for the multiqueue support, which we do advertise.
> fix(virtio-net): advertise the control queue support

- src/drivers/net/gem.rs
- src/drivers/net/rtl8139.rs
- src/drivers/net/virtio/mod.rs
- src/executor/device.rs
Currently, we would copy every single received packet from `DeviceAlloc` to a new `Vec` that is allocated with `GlobalAlloc`. If we use `DeviceAlloc` for the payload of the `RxToken`, we can avoid copying all packets for the special (and common) case of `num_buffers = 1`.
While at it, I refactored the code to make it more readable and avoid allocating the intermediate `Vec` that would be collected into a flattened `Vec<u8>` anyways.
My benchmarking shows that this increases throughput over TCP by roughly ~20%.
> perf(virtio-net): Don't copy packets when num_buffers is 1

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/arch/aarch64/kernel/interrupts.rs
- src/arch/aarch64/kernel/mod.rs
- src/arch/aarch64/kernel/processor.rs
- src/arch/aarch64/kernel/start.rs
- src/lib.rs
- src/scheduler/mod.rs
To realize SMP support, the entry point for new cores is implemented in `smp_start`. The boot core ask the hypervisor to wakeup new cores at this entry point.
In addition, the latest version of arm-gic is used, to support GIC v3 and v4.
This PR depends on #1703 and closes #737
> enable SMP support for aarch64

- src/fd/mod.rs
The main goal of this is to avoid crashes if this flag is set. The flag itself doesn't have any meaning in an unikernel, as we don't have `execve`  or similar process control functionality. 
However, programs [using our newlib](https://github.com/hermit-os/newlib/blob/9ef4bd93cf9cf2cee8d5a05c87b117591dcb4a35/newlib/libc/posix/opendir.c#L85) set this flag and crashe at https://github.com/hermit-os/kernel/blob/d7203edd9df40e42097f3af3568659361f3ddead/src/syscalls/mod.rs#L334
> Added `O_CLOEXEC` flag to OpenOptions

- src/arch/aarch64/mm/paging.rs
- src/arch/riscv64/mm/paging.rs
- src/arch/x86_64/mm/paging.rs
- src/drivers/net/gem.rs
- src/drivers/net/rtl8139.rs
- src/drivers/virtio/virtqueue/mod.rs
- src/drivers/virtio/virtqueue/packed.rs
- src/drivers/virtio/virtqueue/split.rs
This is made possible by https://github.com/hermit-os/kernel/pull/1670.
I can't measure an improvement reliably, but this should be a strict performance improvement and also be visible on the flamegraph.
> perf(drivers): remove `virt_to_phys`

- src/drivers/net/virtio/mmio.rs
- src/drivers/net/virtio/mod.rs
- src/drivers/net/virtio/pci.rs
Split out from #1714 - this PR only fixes the initialization sequence, the logic for choosing a packet length can be fixed separately in that PR later.
> fix(virtio-net): Only initialize virtqueues after feature negotiation

- src/drivers/virtio/virtqueue/mod.rs
`swap_remove` does not need to copy data around, while `remove` emits `memmove` calls that are costly. We do care about preserving ordering, but if there are less than 3 items in the smallvec, `swap_remove` behaves identically. I confirmed that this removes any traces of `memmove` in `receive_packet`.
> perf(virtqueue): Use swap_remove when feasible

- .github/workflows/ci.yml
- xtask/src/ci/qemu.rs
By the PR hermit-os/hermit-rs#719, the command to start `hermit-wasm` changed. Consequently, the CI has to be modified to test `hermit-wasm`.
> Change CI to support hermit-wasm

- src/drivers/virtio/virtqueue/mod.rs
Currently, callers have no way to know whether `pop_front_*` methods returning `None` means that no data was received yet or whether they were trying to pop in the wrong order, e.g. trying to read a packet payload before the header. This would keep repeating infinitely if a driver was reading in the wrong order.
This is always an irrecoverable programming mistake, so let's panic.
> refactor(virtqueue): Don't swallow errors on incorrect pop order

- src/fs/fuse.rs
A C application crashed on negative offsets.
In Linux, this field [is clearly defined as an `uint64_t`](https://github.com/torvalds/linux/blob/e04c78d86a9699d136910cfc0bdcf01087e3267e/include/uapi/linux/fuse.h#L1132), but I'm not sure if this is just the interface definition, or something fixed.
Unfortunately, I couldn't find any documentation on this. What I found was:
- https://man7.org/linux/man-pages/man4/fuse.4.html -> `FUSE_LSEEK` is not documented yet :-/
- libfuse uses `off_t` for all things offset https://libfuse.github.io/doxygen/structfuse__operations.html which is specified [as a _signed_ integer](https://man7.org/linux/man-pages/man3/off_t.3type.html)
So I don't know if this is correct or not, but maybe someone else knows more (@stlankes)
> Fuse Lseek: Don't panic on negative offset

- src/fs/fuse.rs
- src/syscalls/mod.rs
Fixes: https://github.com/hermit-os/kernel/issues/1768
Previously, lseek has not updated the internal offset.
Moreover, any successful call to lseek has returned 0. [POSIX states](https://pubs.opengroup.org/onlinepubs/9699919799/functions/lseek.html) that _Upon successful completion, the resulting offset, as measured in bytes from the beginning of the file, shall be returned. Otherwise, -1 shall be returned, errno shall be set to indicate the error, and the file offset shall remain unchanged._
I think, we can omit the part with the errno and keep using negative numbers to encode an error, but returning the correct file offset seems to be an improvement. (However, in theory, this is a breaking ABI change, but it is very unlikely that any code relies on the current behaviour).
> Fuse lseek fix

- src/drivers/net/virtio/mod.rs
is_multi was removed in 71e97e93589b49a181557232e4bfc1bd271936ed, but the field's doc comment was not.
> docs(virtio-net): remove outdated doc comment

- src/arch/riscv64/kernel/mod.rs
- src/arch/riscv64/kernel/scheduler.rs
- src/arch/riscv64/kernel/start.rs
I have extracted and squashed some changes from https://github.com/hermit-os/kernel/pull/1678 to accelerate merging.
> refactor(riscv64): miscellaneous improvements

- src/drivers/net/virtio/mod.rs
The assert in the `send_packet` function for the length of the buffer, only allowed buffers which were larger than the message. I think we should allow exactly sized buffers.
> fix(virtio): allow exact buffer size in send_packet

- src/arch/aarch64/kernel/interrupts.rs
So this Clippy suggestion is only shown when using build std???
This shows the suggestion:
```bash
cargo clippy --target=aarch64-unknown-none-softfloat -Zbuild-std=core,alloc
```
This does not:
```bash
cargo clippy --target=aarch64-unknown-none-softfloat
```
How peculiar!
> fix(aarch64/interrupts): clippy::unwrap_or_default

- .github/workflows/ci.yml
- Cargo.toml
- src/arch/aarch64/kernel/mmio.rs
- src/arch/aarch64/kernel/mod.rs
- src/arch/aarch64/kernel/serial.rs
- src/arch/mod.rs
- src/arch/riscv64/kernel/devicetree.rs
- src/arch/riscv64/kernel/mmio.rs
- src/arch/riscv64/kernel/mod.rs
- src/arch/riscv64/kernel/serial.rs
- src/arch/x86_64/kernel/mmio.rs
- src/arch/x86_64/kernel/mod.rs
- src/arch/x86_64/kernel/serial.rs
- src/config.rs
- src/console.rs
- src/drivers/console/mmio.rs
- src/drivers/console/mod.rs
- src/drivers/console/pci.rs
- src/drivers/mmio.rs
- src/drivers/mod.rs
- src/drivers/pci.rs
- src/drivers/virtio/mod.rs
- src/drivers/virtio/transport/mmio.rs
- src/drivers/virtio/transport/pci.rs
- src/fd/stdio.rs
- src/init_cell.rs
- src/lib.rs
- src/shell.rs
- xtask/src/ci/qemu.rs
During runtime the kernel checks, if a virtio console device is available, initialize this device and use it to print kernel messages.
A device support at the early stage of the boot process is currently not possible.
This PR depends rust-osdev/virtio-spec-rs#1.
On `x86_64`,  I tested the PR with following command:
```sh
qemu-system-x86_64 -display none -kernel hermit-loader-x86_64 -initrd target/x86_64-unknown-hermit/debug/hello_world -device isa-debug-exit,iobase=0xf4,iosize=0x04 -smp 1 -m 1024M -global virtio-mmio.force-legacy=off -chardev stdio,id=charconsole0 -device virtio-serial-pci,disable-legacy=on -device virtconsole,chardev=charconsole0
```
In case of `aarch64`, I used following command.
```sh
qemu-system-aarch64 -display none -kernel hermit-loader-aarch64 -device …
```
> add support of virtio console according to the VirtIO standard

- src/arch/aarch64/kernel/systemtime.rs
Fixes the RTC reading on aarch64_be.
> fix(aarch64): PL031 read is always little endian

- .github/workflows/ci.yml
Depends on https://github.com/hermit-os/hermit-rs/pull/781.
> ci: don't install nightly for rftrace 0.3.2

- src/syscalls/mod.rs
This is an oversight from https://github.com/hermit-os/kernel/pull/1826, which added several system calls but did not set errno for all appropriate syscalls and even removed setting errno from `sys_close`.
> fix: set errno on appropriate new syscalls

- Cargo.lock
- Cargo.toml
- src/arch/aarch64/kernel/interrupts.rs
- src/arch/aarch64/kernel/mod.rs
- src/arch/aarch64/kernel/pci.rs
- src/arch/aarch64/kernel/processor.rs
- src/arch/aarch64/kernel/systemtime.rs
This PR removes the last dependency on hermit-dtb, completing the migration to the fdt crate, allowing us to archive the hermit-dtb repository.
> fix(aarch64): migrate to fdt crate and remove hermit-dtb

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/arch/aarch64/kernel/interrupts.rs
- src/arch/aarch64/kernel/serial.rs
Bothered me a bit when running the stdin example...
> feat(aarch64): Add support for stdin

- src/fd/mod.rs
- src/fd/socket/tcp.rs
- src/fd/socket/udp.rs
- src/fd/socket/vsock.rs
- src/fs/fuse.rs
- src/fs/mem.rs
- src/fs/mod.rs
- src/fs/uhyve.rs
- src/scheduler/mod.rs
- src/scheduler/task.rs
- src/syscalls/mod.rs
- src/syscalls/socket/mod.rs
Depends on https://github.com/hermit-os/kernel/pull/1891.
> refactor(io): prepare for async I/O traits

- Cargo.toml
- src/arch/aarch64/kernel/serial.rs
- src/arch/x86_64/kernel/serial.rs
- src/errno.rs
Depends on https://github.com/rust-embedded/embedded-hal/pull/697.
> perf(serial): forward serial read to VecDeque impl

- src/drivers/net/virtio/mod.rs
Before checking the send capacity to issue a send token, we need to poll to get the capacity back from completed sends.
> fix(virtio-net): free up send capacity before checking it
